/* =========================================================================
   QUESTOES DE MULTIPLA ESCOLHA
   m = modulo · o = opcoes · c = indice da correta · e = explicacao · img = figura
   ========================================================================= */

const QUESTIONS = [

/* ── 1 ──────────────────────────────────────────────────────────────── */
{ id:'q101', m:1, q:'Na cadeia da transformação, o CONHECIMENTO ocupa qual posição?',
  o:['É o resultado final, depois da informação','São as regras usadas para transformar dado em informação','É sinônimo de dado bruto','É o meio físico onde os dados ficam guardados'],
  c:1, e:'O conhecimento não está na linha <code>dado → processo → informação</code>: ele alimenta o processo por baixo. São as <strong>regras, diretrizes e procedimentos</strong> que fazem a transformação acontecer.' },
{ id:'q102', m:1, q:'"O total de vendas do mês foi R$ 250 mil." Isso é:',
  o:['Dado','Informação','Conhecimento','Um processo'],
  c:1, e:'São dados organizados de forma que ganham valor além do fato em si — ajudam alguém a decidir. Cada venda solta seria o dado; a regra de somar por mês é o conhecimento.' },
{ id:'q103', m:1, q:'Um relatório está tecnicamente correto, mas tem 80 páginas e ninguém consegue decidir nada com ele. Qual característica da boa informação foi violada?',
  o:['Precisa','Verificável','Simples','Econômica'],
  c:2, e:'<strong>Simples</strong>. Informação demais causa sobrecarga. É por isso que "mais dados" não significa automaticamente melhor informação.' },
{ id:'q104', m:1, q:'"Entra lixo, sai lixo" (ELSL) está diretamente ligado a qual característica?',
  o:['Precisa','Flexível','Em tempo','Relevante'],
  c:0, e:'<strong>Precisa</strong> significa "sem erros". Dado errado na entrada gera informação errada na saída — não há processamento que conserte isso.' },
{ id:'q105', m:1, q:'Qual afirmação sobre o VALOR da informação está correta?',
  o:['Depende do volume de dados processados','Depende de quanto ela ajuda alguém a decidir e atingir metas','Depende de ter sido gerada por computador','É sempre proporcional ao custo de produzi-la'],
  c:1, e:'O valor pode ser medido pelo tempo economizado numa decisão ou pelo aumento de lucro. O que importa não é a fonte do processamento — mental, manual ou por computador — e sim se o resultado é útil para quem decide.' },
{ id:'q106', m:1, q:'Qual destas NÃO é uma das características de uma boa informação?',
  o:['Verificável','Econômica','Redundante','Flexível'],
  c:2, e:'As nove são: precisa, completa, econômica, flexível, confiável, relevante, simples, em tempo e verificável. <strong>Redundância</strong> é justamente um dos problemas que a modelagem busca evitar.' },

/* ── 2 ──────────────────────────────────────────────────────────────── */
{ id:'q201', m:2, q:'Qual componente do Sistema de Informação é o mais esquecido nas listas?',
  o:['Entrada','Processamento','Saída','Feedback'],
  c:3, e:'Muita gente lista só entrada, processamento e saída. O <strong>feedback</strong> é a saída usada para ajustar a entrada ou o processamento — sem ele, erros se repetiriam indefinidamente.' },
{ id:'q202', m:2, q:'No exemplo do contracheque, o que corresponde ao PROCESSAMENTO?',
  o:['Coletar as horas trabalhadas','Calcular o salário','Imprimir o contracheque','Corrigir um erro apontado pelo funcionário'],
  c:1, e:'Entrada = coletar as horas. Processamento = calcular o salário. Saída = o contracheque impresso. Feedback = o erro apontado, que volta para corrigir o dado de entrada.' },
{ id:'q203', m:2, q:'Por que dizemos que o banco de dados é a "camada de dados" de um SI?',
  o:['Porque ele produz a saída final do sistema','Porque ele armazena os dados e os devolve durante o processamento e a saída','Porque ele substitui o componente de feedback','Porque ele define a meta do sistema'],
  c:1, e:'O SI coleta, manipula, armazena e dissemina dados. O banco é exatamente o componente que cuida do <strong>armazenamento e da devolução</strong> desses dados.' },
{ id:'q204', m:2, q:'Qual a relação entre "sistema" e "sistema de informação"?',
  o:['São sinônimos','Todo sistema é um SI','Todo SI é um sistema, mas nem todo sistema é de informação','São conceitos independentes'],
  c:2, e:'O SI é o caso <strong>especializado</strong> que lida com dados e tem feedback explícito. Assar um bolo é um sistema, mas não um sistema de informação.' },

/* ── 3 ──────────────────────────────────────────────────────────────── */
{ id:'q301', m:3, q:'Tecnicamente, o que é o MySQL?',
  o:['Um banco de dados','Um SGBD','Um modelo de dados','Uma linguagem de consulta'],
  c:1, e:'MySQL, Oracle e PostgreSQL são <strong>SGBDs</strong> — softwares que gerenciam bancos. O <strong>banco</strong> é o conjunto de dados que eles guardam. Chamar o software de "banco de dados" é o erro clássico da matéria.' },
{ id:'q302', m:3, q:'Na estrutura em duas partes de um sistema de banco de dados, o back end é:',
  o:['A aplicação que o usuário abre','O próprio SGBD','A linguagem SQL','O sistema operacional do servidor'],
  c:1, e:'O <strong>servidor (back end)</strong> é o SGBD: cuida da manipulação de dados, segurança, definição de dados e integridade. Os <strong>clientes (front ends)</strong> são as aplicações executadas sobre ele.' },
{ id:'q303', m:3, q:'Qual característica do SGBD garante que os relacionamentos fiquem armazenados no próprio banco?',
  o:['Controle de acesso','Esquematização','Backup','Controle de redundância'],
  c:1, e:'<strong>Esquematização</strong>: os relacionamentos ficam guardados no banco, garantindo entendimento e integridade — não dependem de estarem documentados só na aplicação.' },
{ id:'q304', m:3, q:'Qual utilitário do DBA cria a versão inicial do banco a partir de arquivos?',
  o:['Reorganização','Rotinas estatísticas','Rotinas de carga','Descarregamento'],
  c:2, e:'As <strong>rotinas de carga</strong> criam a versão inicial. Descarregamento/recarregamento servem para backup e restauração; reorganização rearranja os dados por desempenho; as estatísticas medem tamanho e distribuição.' },
{ id:'q305', m:3, q:'Sobre o controle de redundância num SGBD, é correto afirmar que:',
  o:['O objetivo é sempre eliminar 100% da redundância','O objetivo é minimizar a repetição para dar estabilidade ao modelo','Redundância não é tratada pelo SGBD','Redundância aumenta a integridade'],
  c:1, e:'A característica é <strong>controle</strong> de redundância — o mínimo necessário — e não eliminação absoluta a qualquer custo.' },
{ id:'q306', m:3, q:'O que conta como "objeto" no objetivo de um banco de dados relacional?',
  o:['Apenas tabelas','Tabelas e índices','Tabelas, visões, índices, procedimentos e funções','Apenas os dados das linhas'],
  c:2, e:'O objetivo é armazenar um grupo de objetos do dicionário de dados de forma rápida e segura — e isso inclui <strong>tabelas, visões (views), índices e até procedimentos e funções</strong> armazenados no banco.' },

/* ── 4 ──────────────────────────────────────────────────────────────── */
{ id:'q401', m:4, q:'Qual a diferença-chave entre o modelo hierárquico e o modelo de rede?',
  o:['O número de pais que um registro pode ter','O uso de chaves primárias','A existência de métodos nos registros','O uso de tabelas bidimensionais'],
  c:0, e:'<strong>Hierárquico: um pai por filho</strong> (árvore). <strong>Rede: vários pais</strong>. Por isso a rede é considerada uma <em>generalização</em> do hierárquico.' },
{ id:'q402', m:4, q:'De onde vem o nome do modelo "relacional"?',
  o:['Do fato de ser o único modelo com relacionamentos','Do termo matemático "relação", que designa uma tabela','Do relacionamento entre cliente e servidor','Da relação entre dados e informação'],
  c:1, e:'O nome vem de <strong>relação</strong>, o termo matemático para tabela. Todos os modelos representam relações entre dados — o relacional as organiza em relações no sentido formal.' },
{ id:'q403', m:4, q:'Qual exemplo do mundo real é melhor representado pelo modelo hierárquico?',
  o:['Funcionário que participa de vários projetos','Estrutura de pastas do sistema operacional','Aluno matriculado em várias disciplinas','Produto fornecido por vários fornecedores'],
  c:1, e:'Na estrutura de pastas, cada pasta tem <strong>um único pai</strong> — é uma árvore. Os outros três exemplos têm "vários pais" e pedem o modelo de rede (ou um N:N no relacional).' },
{ id:'q404', m:4, q:'O modelo OBJETO-RELACIONAL se caracteriza por:',
  o:['Representar dados e processos em um único objeto','Combinar orientação a objetos com linhas e colunas','Ser uma árvore de registros','Permitir que um filho tenha vários pais'],
  c:1, e:'Ele combina o modelo <strong>orientado a objetos</strong> (propriedades + métodos) com o <strong>relacional</strong> (linhas e colunas). Representar dados e processos num único objeto é o modelo <em>Objeto</em>.' },

/* ── 5 ──────────────────────────────────────────────────────────────── */
{ id:'q501', m:5, q:'Qual era o principal PROBLEMA da arquitetura cliente/servidor de 2 camadas?',
  o:['O custo do mainframe','Atualizar o aplicativo em cada estação','A falta de banco de dados','A lentidão do browser'],
  c:1, e:'Como a <strong>regra de negócio ficava no cliente</strong>, qualquer mudança exigia atualizar o executável máquina a máquina. Imagine 1000 estações. O custo de hardware era o problema do modelo <em>centralizado</em>.' },
{ id:'q502', m:5, q:'O que o modelo de 3 camadas tira do cliente?',
  o:['A apresentação','A regra de negócio','Os dados','O sistema operacional'],
  c:1, e:'A 3 camadas centraliza a <strong>regra de negócio</strong> num servidor de aplicação. Fica: apresentação no cliente, lógica no servidor de aplicação, dados no banco. É a de 4 camadas que também tira a apresentação.' },
{ id:'q503', m:5, q:'Qual a diferença central entre 3 e 4 camadas?',
  o:['A de 4 camadas tem banco de dados; a de 3 não','A de 4 camadas também tira a apresentação do cliente, que passa a ser um browser','A de 3 camadas é distribuída','A de 4 camadas dispensa servidor de aplicação'],
  c:1, e:'Na de 4 camadas a apresentação vai para um <strong>servidor web</strong> (IIS, Apache) e o acesso passa a ser por <strong>browser</strong>. Vantagem: nada é instalado máquina a máquina.' },
{ id:'q504', m:5, q:'"Três camadas significa obrigatoriamente três máquinas físicas." Esta afirmação é:',
  o:['Verdadeira','Falsa — são camadas lógicas','Verdadeira apenas em ambiente web','Falsa — são sempre quatro máquinas'],
  c:1, e:'São <strong>camadas lógicas</strong> — apresentação, lógica e dados. Elas <em>podem</em> estar em servidores diferentes, mas isso não é obrigatório.' },
{ id:'q505', m:5, q:'Qual o cuidado necessário ao adotar modelos de 3 ou mais camadas?',
  o:['Aumentar o número de estações','Cuidar do desempenho e do dimensionamento dos servidores','Reinstalar o cliente em cada máquina','Abandonar o banco relacional'],
  c:1, e:'Ao centralizar serviços, <strong>processamento e memória tornam-se críticos</strong>. Ganham-se muitas vantagens, mas o servidor precisa ser bem dimensionado.' },
{ id:'q506', m:5, q:'O que caracteriza o processamento distribuído?',
  o:['Uma máquina faz tudo','Uma única tarefa de processamento se estende por várias máquinas em rede','O cliente guarda uma cópia do banco','A apresentação roda no servidor web'],
  c:1, e:'No distribuído, máquinas conectadas em rede fazem com que <strong>uma tarefa se espalhe por várias máquinas</strong>, com a comunicação feita por software de gerenciamento de rede.' },

/* ── 6 ──────────────────────────────────────────────────────────────── */
{ id:'q601', m:6, q:'Qual é a ordem correta das etapas da modelagem?',
  o:['DER → MER → Físico → Relacional','MER → DER → Relacional → Físico','Relacional → MER → DER → Físico','Físico → Relacional → DER → MER'],
  c:1, e:'<code>Enunciado → MER (conceitual) → DER (o desenho) → Modelo Relacional (tabelas) → Modelo Físico (o SGBD)</code>. É o fio condutor da disciplina inteira.', img:'conceito-pipeline-modelagem.png' },
{ id:'q602', m:6, q:'Qual a diferença entre MER e DER?',
  o:['MER é o desenho; DER é o modelo','MER é o modelo (as ideias e decisões); DER é a representação gráfica dele','MER é para SGBD relacional; DER para hierárquico','Não há diferença — são exatamente sinônimos'],
  c:1, e:'O <strong>MER</strong> é o conjunto de ideias e decisões. O <strong>DER</strong> é o desenho desse modelo, usando os símbolos padrão. Muita gente usa como sinônimo, mas na prova a distinção conta.' },
{ id:'q603', m:6, q:'No DER, o que representa uma ELIPSE DUPLA?',
  o:['Entidade fraca','Atributo-chave','Atributo multivalorado','Especialização'],
  c:2, e:'Elipse = atributo. Elipse <strong>sublinhada</strong> = atributo-chave. Elipse <strong>dupla</strong> = multivalorado. Retângulo duplo = entidade fraca. Triângulo = especialização.', img:'conceito-simbolos-der.png' },
{ id:'q604', m:6, q:'Quais são os DOIS problemas centrais que a modelagem de dados busca evitar?',
  o:['Lentidão e custo de licença','Redundância e desperdício de espaço','Concorrência e deadlock','Erro de sintaxe e falha de backup'],
  c:1, e:'<strong>Redundância</strong> (com duas cópias, nunca se sabe em qual confiar) e <strong>desperdício de espaço</strong>. A solução é isolar informações em tabelas e ligá-las por um código comum.' },
{ id:'q605', m:6, q:'Por que o MER é considerado "universal"?',
  o:['Porque funciona em qualquer sistema operacional','Porque descreve o negócio e não depende de nenhum SGBD','Porque usa apenas a língua inglesa','Porque foi padronizado pela ISO'],
  c:1, e:'O MER é <strong>conceitual</strong>: descreve o negócio, não um produto. Por isso pode ser implementado em qualquer SGBD — é uma das vantagens listadas na aula.' },
{ id:'q606', m:6, q:'O que acontece com os losangos quando o modelo conceitual vira relacional?',
  o:['Viram tabelas, sempre','Somem: viram FK (1:N e 1:1) ou tabelas (N:N)','Viram colunas do tipo VARCHAR','Permanecem como losangos'],
  c:1, e:'No relacional não existe losango. Relacionamentos viram <strong>FK</strong> nos casos 1:N e 1:1, e <strong>tabelas associativas</strong> no caso N:N.' },

/* ── 7 ──────────────────────────────────────────────────────────────── */
{ id:'q701', m:7, q:'Ao ler um enunciado, os SUBSTANTIVOS costumam indicar:',
  o:['Relacionamentos','Entidades','Cardinalidades','Chaves estrangeiras'],
  c:1, e:'Substantivos → entidades. <strong>Verbos</strong> → relacionamentos. É a primeira varredura de qualquer exercício de modelagem.' },
{ id:'q702', m:7, q:'Qual o número mínimo de atributos para justificar uma entidade?',
  o:['Um','Dois','Três','Não há mínimo'],
  c:1, e:'No mínimo <strong>dois</strong>. Uma entidade com um único atributo normalmente será <strong>agregada</strong> a outra.' },
{ id:'q703', m:7, q:'"Endereço = rua, número, complemento, cidade, CEP" é um atributo:',
  o:['Simples','Composto','Multivalorado','Derivado'],
  c:1, e:'<strong>Composto</strong>: um valor dividido em subatributos. Ao virar tabela, "achata-se" em colunas. Não confunda com <strong>multivalorado</strong>, que são vários valores do mesmo tipo (vários telefones).' },
{ id:'q704', m:7, q:'A notação <code>Funcionario(numf, nome, telefone*)</code> indica que telefone é:',
  o:['Chave primária','Chave estrangeira','Multivalorado','Composto'],
  c:2, e:'O <code>*</code> após o nome marca um atributo <strong>multivalorado</strong>. No DER isso aparece como <strong>elipse dupla</strong>; no relacional, vira uma tabela nova.' },
{ id:'q705', m:7, q:'Qual é a modelagem CORRETA para os vários telefones de um cliente?',
  o:['<code>CLIENTE(cod_cli, nome, fone1, fone2, fone3)</code>','<code>CLIENTE(cod_cli, nome, fones)</code> com os números separados por vírgula','Uma tabela <code>CLIENTE_FONE(cod_cli, fone)</code>','Um campo de texto livre'],
  c:2, e:'Colunas fixas limitam a quantidade, desperdiçam espaço e dificultam consultas. Multivalorado <strong>sempre vira tabela</strong>, com PK composta <code>(cod_cli, fone)</code>.' },
{ id:'q706', m:7, q:'A entidade <code>CD</code> e o CD "Mais do Mesmo" são, respectivamente:',
  o:['Instância e entidade','Entidade e instância','Atributo e tupla','Tupla e atributo'],
  c:1, e:'A <strong>entidade</strong> é a classe/categoria; a <strong>instância</strong> é a ocorrência específica. Confundir os dois é erro comum ao identificar entidades num enunciado.' },
{ id:'q707', m:7, q:'Criar uma entidade "Cor" para representar a cor de um produto é:',
  o:['Correto — toda característica vira entidade','Um erro: cor é apenas um atributo','Correto apenas se houver mais de 10 cores','Um caso de especialização'],
  c:1, e:'Se algo apenas <strong>descreve</strong>, é atributo. Só vira entidade o que tem <strong>características próprias e várias ocorrências</strong> que precisam ser guardadas.' },

/* ── 8 ──────────────────────────────────────────────────────────────── */
{ id:'q801', m:8, q:'Quais são as três exigências do conteúdo de uma chave primária?',
  o:['Numérico, curto e sequencial','Único, exclusivo e imutável','Nulo, único e indexado','Composto, textual e ordenável'],
  c:1, e:'A PK identifica unicamente cada tupla, e todos os demais atributos dependem dela. Por isso precisa ser <strong>única, exclusiva e imutável</strong>.' },
{ id:'q802', m:8, q:'Em <code>ITENS_PEDIDO</code>, por que a PK é <code>NR_PEDIDO + ITEM</code>?',
  o:['Para acelerar a consulta','Porque o mesmo NR_PEDIDO tem vários itens — só a combinação identifica uma linha','Porque ITEM é chave estrangeira','Porque NR_PEDIDO pode ser nulo'],
  c:1, e:'É uma <strong>chave composta</strong>: a <em>união</em> dos atributos garante o acesso a uma única linha. Achar que um deles sozinho identifica é o erro clássico.' },
{ id:'q803', m:8, q:'Qual chave serve para CLASSIFICAÇÃO e PESQUISA, sem identificar unicamente?',
  o:['Primária','Estrangeira','Secundária','Composta'],
  c:2, e:'A <strong>chave secundária</strong> serve para buscas e ordenações (por data, valor, status). Confundi-la com a estrangeira — que liga tabelas — é erro frequente.' },
{ id:'q804', m:8, q:'Um mesmo atributo pode ser PK e FK ao mesmo tempo?',
  o:['Nunca','Sim, em entidades fracas e tabelas associativas','Apenas em relacionamentos 1:1','Apenas no modelo físico'],
  c:1, e:'Acontece exatamente nesses dois casos. Ex.: <code>CLIENTE_FONE(COD_CLI [PK/FK], FONE [PK])</code> — <code>COD_CLI</code> compõe a PK e referencia CLIENTE.' },
{ id:'q805', m:8, q:'Por que o atributo "nome" costuma ser uma PK ruim?',
  o:['Porque ocupa muito espaço','Porque pode repetir e pode mudar','Porque não pode ser indexado','Porque é do tipo texto'],
  c:1, e:'A PK precisa ser <strong>única e imutável</strong>. Nome falha nas duas exigências. Se não houver atributo natural adequado, o certo é <strong>criar um</strong> (um código sequencial).' },
{ id:'q806', m:8, q:'A FK responde a qual pergunta?',
  o:['"Quem sou eu?"','"Quem eu referencio / de quem eu dependo?"','"Quantos de cada lado?"','"Quantas entidades participam?"'],
  c:1, e:'Macete da aula: <strong>PK = "quem sou eu?"</strong> (identifica o registro na própria tabela). <strong>FK = "quem eu referencio?"</strong> (aponta para a PK de outra).' },

/* ── 9 ──────────────────────────────────────────────────────────────── */
{ id:'q901', m:9, q:'Num relacionamento 1:N, onde fica a chave estrangeira?',
  o:['No lado 1','No lado N','Numa tabela nova','Nos dois lados'],
  c:1, e:'O lado <strong>1</strong> tem os dados básicos; a FK desce para o lado <strong>N</strong>. Inverter isso quebra o modelo relacional inteiro.', img:'conceito-mapeamento.png' },
{ id:'q902', m:9, q:'Por que um relacionamento N:N não pode ser implementado diretamente numa tabela?',
  o:['Porque o SGBD não suporta','Porque cada linha tem um valor por coluna, e N:N exige múltiplas combinações','Porque falta chave primária','Porque N:N não existe no modelo relacional conceitual'],
  c:1, e:'Ele é transformado em <strong>dois relacionamentos 1:N</strong> com uma <strong>entidade associativa</strong> no meio, cuja PK é a união das duas chaves.' },
{ id:'q903', m:9, q:'Ao encontrar um relacionamento 1:1, qual pergunta o professor manda fazer?',
  o:['"Onde coloco a tabela associativa?"','"Essas duas entidades não deveriam ser uma só? E amanhã não vira 1:N?"','"Qual atributo é multivalorado?"','"Quantas entidades participam?"'],
  c:1, e:'O 1:1 às vezes indica que as duas tabelas poderiam ser unidas. E vale checar se a regra de negócio não pode mudar, transformando-o em 1:N.' },
{ id:'q904', m:9, q:'Quais são os TRÊS elementos de um relacionamento?',
  o:['Nome, opcionalidade e cardinalidade','PK, FK e índice','Entidade, atributo e tupla','Grau, ordem e peso'],
  c:0, e:'Um <strong>nome</strong> (que é um verbo), a <strong>opcionalidade</strong> (deve/pode) e a <strong>cardinalidade</strong> (uma única / uma ou mais).' },
{ id:'q905', m:9, q:'"Um autor escreve vários livros e um livro pode ter vários autores." Qual a cardinalidade e o que ela gera?',
  o:['1:N — FK em LIVRO','1:1 — FK no lado total','N:N — tabela associativa AUTOR_LIVRO','1:N — FK em AUTOR'],
  c:2, e:'Os dois lados são "muitos", então é <strong>N:N</strong> — e todo N:N gera uma tabela associativa com as duas PKs.', img:'conceito-cardinalidades.png' },
{ id:'q906', m:9, q:'Em <code>CLIENTE 1 — N PEDIDO</code>, qual comando está correto?',
  o:['<code>ALTER TABLE cliente ADD nr_pedido ...</code>','<code>CREATE TABLE pedido (..., cod_cli INTEGER REFERENCES cliente)</code>','<code>CREATE TABLE cliente_pedido (cod_cli, nr_pedido)</code>','Nenhum — 1:N não gera nada'],
  c:1, e:'A FK <code>cod_cli</code> fica em <strong>PEDIDO</strong> (o lado N). Criar uma tabela associativa aqui seria o erro de tratar 1:N como se fosse N:N.' },

/* ── 10 ─────────────────────────────────────────────────────────────── */
{ id:'q1001', m:10, q:'O GRAU de um relacionamento indica:',
  o:['Quantas ocorrências de cada lado','Quantas entidades participam do relacionamento','Quantos atributos o relacionamento tem','Quantas FKs são geradas'],
  c:1, e:'<strong>Grau conta entidades</strong> (1, 2, 3...). <strong>Cardinalidade conta ocorrências de cada lado</strong> (1:1, 1:N, N:N). São perguntas diferentes e caem juntas em prova.' },
{ id:'q1002', m:10, q:'"Funcionário supervisiona funcionário" é um relacionamento de grau:',
  o:['1 (unário)','2 (binário) — porque Funcionário aparece duas vezes','3 (ternário)','Indefinido'],
  c:0, e:'É <strong>grau 1</strong>: há uma <em>única</em> entidade participando, mesmo que ela apareça nas duas pontas do losango. Dizer "grau 2 porque aparece duas vezes" é o erro clássico.' },
{ id:'q1003', m:10, q:'Ao ler tabelas, o que indica um auto-relacionamento?',
  o:['Uma tabela intermediária com duas FKs','Uma FK que aponta para a própria tabela','Uma PK composta','Uma coluna com valores repetidos'],
  c:1, e:'Ex.: <code>empregado(ident PK, nome, super_ident REFERENCES empregado)</code>. A FK volta para a mesma tabela — assinatura do auto-relacionamento.' },
{ id:'q1004', m:10, q:'Por que NÃO se cria uma entidade "Supervisor" separada de "Funcionário"?',
  o:['Porque o SGBD não permite','Porque o supervisor É um funcionário — criar outra entidade duplicaria a informação','Porque supervisores não têm atributos','Porque isso geraria um relacionamento ternário'],
  c:1, e:'O caso correto é <strong>auto-relacionamento</strong>, com rótulos de papel nas ligações ("supervisiona" / "é supervisionado por").' },
{ id:'q1005', m:10, q:'"Uma peça pode ser composta de várias peças, e cada peça pode compor várias outras." Qual a cardinalidade desse auto-relacionamento?',
  o:['1:1','1:N','N:N, geralmente com atributo quantidade','Não tem cardinalidade — é grau 1'],
  c:2, e:'Auto-relacionamento é <strong>grau 1</strong> e <em>ainda assim tem cardinalidade</em>. Aqui é <strong>N:N</strong>, tipicamente com o atributo <code>quantidade</code> no relacionamento.' },
{ id:'q1006', m:10, q:'Quando um relacionamento ternário deve ser substituído por agregação?',
  o:['Sempre','Nunca','Quando o ternário fica artificial e um relacionamento precisa participar de outro','Quando há mais de 3 atributos'],
  c:2, e:'Exemplo do slide: em vez do ternário MRP (Materiais, Requisições, Pedidos), separa-se em "Itens de requisição" agregado e "Itens de pedido" ligando a Pedidos.' },

/* ── 11 ─────────────────────────────────────────────────────────────── */
{ id:'q1101', m:11, q:'Como uma entidade fraca aparece no DER?',
  o:['Losango duplo','Retângulo duplo','Elipse dupla','Triângulo'],
  c:1, e:'<strong>Retângulo duplo</strong>. Losango = relacionamento; elipse dupla = multivalorado; triângulo = especialização.', img:'conceito-casos-especiais.png' },
{ id:'q1102', m:11, q:'Qual a consequência de DEPENDENTE ser uma entidade fraca?',
  o:['Ela não pode ter atributos próprios','Sua PK deve incluir a chave da entidade forte','Ela não gera tabela no relacional','Ela vira uma coluna de FUNCIONARIO'],
  c:1, e:'Dois funcionários podem ter um dependente chamado "Pedro" — só o nome não identifica. Por isso a PK é composta: <code>(ident_emp, nome)</code>.' },
{ id:'q1103', m:11, q:'Como se chama o relacionamento que liga a entidade fraca à forte?',
  o:['Relacionamento associativo','Relacionamento identificador','Relacionamento total','Relacionamento agregado'],
  c:1, e:'É o <strong>relacionamento identificador</strong> — ele é o que permite identificar a entidade fraca, já que ela não se identifica sozinha.' },
{ id:'q1104', m:11, q:'O atributo <code>horas</code> em <code>TrabalhaNo(IdentEmp, ProjNum, Horas)</code> pertence a:',
  o:['Empregado','Projeto','Ao relacionamento entre os dois','A nenhum — é derivado'],
  c:2, e:'<code>horas</code> depende da <strong>combinação</strong> empregado + projeto. É o que caracteriza uma <strong>associativa atributiva</strong>. Colocá-lo dentro de uma das entidades é erro comum.', img:'caso2-empregado-projeto-der.png' },
{ id:'q1105', m:11, q:'Entidade FRACA e entidade ASSOCIATIVA podem se parecer no desenho. O que realmente as distingue?',
  o:['O número de atributos','A motivação: a fraca vem de dependência de existência; a associativa, de resolver um N:N','A cor do símbolo','A fraca nunca tem FK'],
  c:1, e:'As duas podem ter retângulo duplo e chave composta. Mas a <strong>fraca</strong> existe porque depende de outra para existir; a <strong>associativa</strong> nasce para resolver um N:N ou guardar atributos do relacionamento.' },
{ id:'q1106', m:11, q:'Ao encontrar uma tabela intermediária com duas FKs formando a PK, você conclui que:',
  o:['É uma entidade fraca','É um N:N resolvido','É um erro de modelagem','É um auto-relacionamento'],
  c:1, e:'Toda tabela intermediária desse tipo é normalmente um <strong>N:N resolvido</strong> — uma entidade associativa.' },

/* ── 12 ─────────────────────────────────────────────────────────────── */
{ id:'q1201', m:12, q:'A relação "é-um" corresponde a:',
  o:['Relacionamento comum','Especialização','Agregação','Entidade fraca'],
  c:1, e:'"Uma secretária <strong>é uma</strong> funcionária" — especialização, com herança de atributos. "Um funcionário <strong>tem um</strong> departamento" é relacionamento comum.' },
{ id:'q1202', m:12, q:'O símbolo "+" numa especialização indica:',
  o:['Que a especialização é total','Que a especialização é exclusiva — a entidade pertence a apenas um subconjunto','Que há mais de duas subclasses','Que os atributos são somados'],
  c:1, e:'É o "ou exclusivo": a ocorrência pertence a <strong>apenas um</strong> dos subconjuntos.' },
{ id:'q1203', m:12, q:'Especialização e generalização são:',
  o:['Conceitos independentes','O mesmo relacionamento em direções opostas','Sinônimos exatos','Casos de agregação'],
  c:1, e:'<strong>Especialização</strong> = geral → específico (top-down). <strong>Generalização</strong> = específicos → geral (bottom-up).' },
{ id:'q1204', m:12, q:'O que é AGREGAÇÃO?',
  o:['Juntar duas entidades numa só','Tratar um relacionamento como entidade para que participe de outro relacionamento','Somar atributos de várias entidades','Transformar N:N em 1:N'],
  c:1, e:'Ex.: <code>MEDICO — ATENDE — PACIENTE</code> e depois <code>HOSPITAL — ACOMPANHA — [MEDICO ATENDE PACIENTE]</code>. O relacionamento ATENDE foi "empacotado".' },
{ id:'q1205', m:12, q:'Em <code>ENGENHEIRO(cpf, crea, especialidade)</code> especializando <code>FUNCIONARIO(cpf, ...)</code>, o cpf do engenheiro é:',
  o:['Apenas PK','Apenas FK','PK e FK ao mesmo tempo','Chave secundária'],
  c:2, e:'É assim que a chave é herdada na especialização: <code>cpf VARCHAR(11) PRIMARY KEY REFERENCES funcionario</code>.', img:'caso3-engenho-abc-der.png' },
{ id:'q1206', m:12, q:'AGREGAÇÃO × ENTIDADE ASSOCIATIVA — qual a diferença?',
  o:['São exatamente a mesma coisa','A associativa resolve um N:N entre duas entidades; a agregação empacota um relacionamento para ligá-lo a uma terceira entidade','A agregação só existe no modelo físico','A associativa não gera tabela'],
  c:1, e:'As duas "transformam relacionamento em algo que se relaciona", mas com finalidades diferentes.' },

/* ── 13 ─────────────────────────────────────────────────────────────── */
{ id:'q1301', m:13, q:'O que caracteriza uma violação de integridade referencial?',
  o:['Uma PK nula','Uma FK apontando para um registro que não existe','Uma tabela sem índice','Um atributo derivado armazenado'],
  c:1, e:'Ex.: um pedido com <code>cod_cli = 99</code> quando não existe cliente 99. Isso deixa um registro <strong>órfão</strong>.' },
{ id:'q1302', m:13, q:'Ao excluir um cliente que possui pedidos, quais são as duas estratégias possíveis?',
  o:['Ignorar ou duplicar','Bloquear (RESTRICT) ou propagar em cascata (CASCADE)','Renomear ou arquivar','Indexar ou desindexar'],
  c:1, e:'Ou o SGBD <strong>impede</strong> a exclusão do pai, ou <strong>apaga/altera os dependentes junto</strong>. A escolha é declarada na FK.' },
{ id:'q1303', m:13, q:'Integridade de ENTIDADE cuida de quê?',
  o:['Da FK — referências válidas','Da PK — identificador único e não nulo','Do backup','Da normalização'],
  c:1, e:'São regras complementares: a <strong>referencial</strong> cuida da FK; a <strong>de entidade</strong> cuida da PK.' },
{ id:'q1304', m:13, q:'"A integridade referencial funciona automaticamente, sem declarar nada." Esta afirmação é:',
  o:['Verdadeira','Falsa — ela precisa ser declarada via FK e constraints no modelo físico','Verdadeira apenas em bancos relacionais','Verdadeira apenas com CASCADE'],
  c:1, e:'Sem declarar a <code>FOREIGN KEY</code>, o SGBD não tem como saber que existe uma dependência a proteger.' },

/* ── 14 ─────────────────────────────────────────────────────────────── */
{ id:'q1401', m:14, q:'Um relacionamento 1:N no mapeamento:',
  o:['Sempre gera uma tabela nova','Não gera tabela — a chave do lado 1 desce como FK para o lado N','Gera duas tabelas','Gera uma chave secundária'],
  c:1, e:'E essa FK <strong>não</strong> faz parte da PK do lado N. <em>Obs.: um 1:N pode gerar tabela quando não há totalidade na associação.</em>' },
{ id:'q1402', m:14, q:'Um relacionamento N:N no mapeamento gera:',
  o:['Uma FK no lado escolhido','Uma tabela com as PKs das duas entidades + os atributos do relacionamento','Uma chave secundária','Nada — resolve-se com índice'],
  c:1, e:'Ex.: <code>Emprestimos(COD_usuario, No_tombo, data_ret, data_dev)</code> ligando Usuários e Livros.' },
{ id:'q1403', m:14, q:'Num relacionamento 1:1, como se decide para onde vai a chave?',
  o:['Vai sempre para a tabela com mais atributos','Observa-se a participação total — a chave vai para o lado total','Vai sempre para a primeira tabela do enunciado','Cria-se uma tabela associativa'],
  c:1, e:'Exemplo da aula: "todo país tem uma capital, mas nem toda cidade é capital" → a tabela <strong>Países</strong> recebe <code>codigo_capital</code>.' },
{ id:'q1404', m:14, q:'Qual a diferença entre a chave transposta num 1:N comum e numa entidade fraca?',
  o:['Não há diferença','No 1:N ela é só FK e fica fora da PK; na fraca ela entra na PK','No 1:N ela entra na PK; na fraca fica fora','Na fraca não há chave transposta'],
  c:1, e:'É a pegadinha mais recorrente do mapeamento. Mesma operação, consequências diferentes na chave.' },
{ id:'q1405', m:14, q:'Quando a SEGUNDA forma de mapear especialização (só as tabelas de baixo) é permitida?',
  o:['Sempre','Nunca','Só se a especialização for mutuamente exclusiva E total','Só se houver exatamente duas subclasses'],
  c:2, e:'A <strong>forma 1</strong> (tabela do geral + uma por especialização) é sempre válida. A <strong>forma 2</strong> exige exclusividade e totalidade.' },
{ id:'q1406', m:14, q:'Um atributo multivalorado, no mapeamento, gera:',
  o:['Colunas numeradas na mesma tabela','Uma tabela nova com o atributo + a PK da entidade','Uma chave secundária','Um índice composto'],
  c:1, e:'Ex.: <code>Livros(No_tombo, ...)</code> e <code>Autores(No_tombo, autor)</code>. Não criar essa tabela é um dos erros clássicos.' },
{ id:'q1407', m:14, q:'Uma entidade FRACA vira que tipo de tabela?',
  o:['Uma tabela com PK própria e independente','Uma tabela cuja PK inclui a PK da entidade forte','Uma coluna dentro da entidade forte','Nenhuma — ela não é mapeada'],
  c:1, e:'Ex.: <code>Carros(chassi, ...)</code> e <code>Reparos(chassi, data, tipo, valor)</code> — a chave transposta <strong>compõe</strong> a PK da fraca.' },
{ id:'q1408', m:14, q:'Qual destes é um ERRO de mapeamento?',
  o:['Colocar a FK no lado N de um 1:N','Criar uma tabela associativa para um N:N','Criar uma tabela para um relacionamento 1:N comum','Incluir a PK da forte na PK da fraca'],
  c:2, e:'Um 1:N comum <strong>não precisa de tabela</strong> — basta a FK no lado N. Os outros três estão corretos.' },

/* ── 15 ─────────────────────────────────────────────────────────────── */
{ id:'q1501', m:15, q:'Qual é a "regra de ouro" do aspecto temporal?',
  o:['Atual = passado; temporal = futuro','Atual = como está agora; temporal = agora + como esteve no passado','Atual = com data; temporal = sem data','Atual = 1:N; temporal = 1:1'],
  c:1, e:'É a definição que a prova cobra. E a decisão "guardar histórico ou não" muda o modelo inteiro.' },
{ id:'q1502', m:15, q:'Quando se quer guardar o HISTÓRICO de um atributo, ele:',
  o:['Ganha uma coluna extra de data','Vira uma nova entidade, com DATA','Vira chave estrangeira','É removido do modelo'],
  c:1, e:'Ex.: salário. Só o atual → <code>EMPREGADO(cod_emp, salario)</code>. Com histórico → <code>EMPREGADO (1) — (N) SALARIO(data, valor)</code>.', img:'conceito-aspecto-temporal.png' },
{ id:'q1503', m:15, q:'Um relacionamento 1:1 que passa a guardar histórico vira:',
  o:['1:N','N:N','Permanece 1:1 com uma coluna data','Uma especialização'],
  c:1, e:'Com histórico, os <strong>dois lados</strong> viram "muitos": um empregado passou por várias mesas e uma mesa foi de vários empregados. O mesmo vale para 1:N → N:N.' },
{ id:'q1504', m:15, q:'Por que a DATA passa a ser identificadora do relacionamento?',
  o:['Para ordenar os registros','Porque o mesmo par pode se relacionar mais de uma vez','Porque o SGBD exige','Porque a PK não pode ser composta'],
  c:1, e:'Se João foi alocado à Mesa 10 em 2023 e de novo em 2025, "João + Mesa 10" não distingue as duas ocorrências. A DATA é o que as diferencia.' },
{ id:'q1505', m:15, q:'Qual a diferença entre ARQUIVAR dados antigos e guardar ESTATÍSTICAS?',
  o:['Arquivar guarda o resumo; estatística guarda o detalhe','Arquivar guarda o detalhe fora do BD; estatística guarda só o resumo e descarta o detalhe','São a mesma coisa','Arquivar só vale para relacionamentos'],
  c:1, e:'E o arquivamento precisa ser <strong>planejado</strong>: recuperar uma entidade exige recuperar aquelas de que ela depende — a chamada recuperação em cascata.' },
{ id:'q1506', m:15, q:'Guardar o histórico de salários como <code>salario1, salario2, salario3</code> é:',
  o:['A modelagem correta','Um erro — o correto é criar uma entidade com DATA','Aceitável se forem no máximo 3','Um caso de especialização'],
  c:1, e:'É o mesmo erro do atributo multivalorado em colunas fixas. O correto é <code>HISTORICO_SALARIO(cod_emp, data, valor)</code> com PK <code>(cod_emp, data)</code>.' },

/* ── 16 ─────────────────────────────────────────────────────────────── */
{ id:'q1601', m:16, q:'O que a 1FN elimina?',
  o:['Toda a redundância do banco','Os grupos de repetição','Os atributos calculados','As dependências transitivas'],
  c:1, e:'Cuidado: 1FN <strong>não</strong> é "eliminar toda repetição". É eliminar <strong>grupos de repetição</strong> (e multivalorados/aninhados). A organização continua na 2FN e 3FN.', img:'conceito-formas-normais.png' },
{ id:'q1602', m:16, q:'A 2FN só faz sentido em tabelas que têm:',
  o:['Chave estrangeira','Chave composta','Atributos derivados','Mais de 10 colunas'],
  c:1, e:'A pergunta da 2FN é "os atributos não-chave dependem da <strong>chave inteira</strong>?". Sem chave composta, não há como haver dependência parcial.' },
{ id:'q1603', m:16, q:'A 3FN verifica duas coisas. Quais?',
  o:['Grupos de repetição e chaves compostas','Não-chave que depende de outro não-chave, e atributos calculados/derivados','FKs inválidas e PKs nulas','Cardinalidade e grau'],
  c:1, e:'Dependência <strong>transitiva</strong> (não-chave → não-chave) e a remoção de <strong>derivados</strong>, que são fonte clássica de inconsistência.' },
{ id:'q1604', m:16, q:'No Pedido de Compra, em qual forma normal o MATERIAL sai de ITENS_PEDIDO?',
  o:['1FN','2FN','3FN','Não sai'],
  c:1, e:'Na <strong>2FN</strong>: a chave é <code>NR_PEDIDO + ITEM</code> e <code>MATERIAL</code> não depende da chave inteira. <code>QUANTIDADE</code>, que depende dos dois, fica.' },
{ id:'q1605', m:16, q:'Por que <code>QTD_TOTAL</code> é removido na 3FN?',
  o:['Porque é chave estrangeira','Porque é derivado (soma dos itens) e pode divergir da soma real','Porque é multivalorado','Porque depende só de parte da chave'],
  c:1, e:'Manter um total calculado é fonte clássica de <strong>inconsistência</strong>: basta um item mudar para o total armazenado ficar errado.' },
{ id:'q1606', m:16, q:'Dependência PARCIAL e dependência TRANSITIVA correspondem, respectivamente, a:',
  o:['1FN e 2FN','2FN e 3FN','3FN e 1FN','1FN e 3FN'],
  c:1, e:'<strong>Parcial</strong> (2FN) = depende de <em>parte</em> da chave composta. <strong>Transitiva</strong> (3FN) = não-chave depende de <em>outro não-chave</em>.' },
{ id:'q1607', m:16, q:'Qual destes é um erro clássico de normalização?',
  o:['Aplicar 1FN antes da 2FN','Aplicar 2FN numa tabela sem chave composta','Remover atributos derivados na 3FN','Separar assuntos diferentes em tabelas'],
  c:1, e:'A 2FN só se aplica a tabelas com chave composta. Os outros três descrevem procedimentos <strong>corretos</strong>.' },
{ id:'q1608', m:16, q:'Qual é a ideia central da normalização?',
  o:['Reduzir o número de tabelas','Não misturar assuntos diferentes na mesma tabela','Acelerar as consultas com índices','Eliminar chaves estrangeiras'],
  c:1, e:'A cada forma normal, um "assunto" novo ganha sua própria tabela. Os objetivos: evitar repetição, evitar inconsistência, organizar e facilitar alterações.' },

/* ── 17 ─────────────────────────────────────────────────────────────── */
{ id:'q1701', m:17, q:'Neste DER, o que o retângulo duplo de DEPENDENTE indica?', img:'caso2-empregado-projeto-der.png',
  o:['Que a entidade tem duas chaves','Que é uma entidade fraca, dependente de EMPREGADO','Que participa de dois relacionamentos','Que é uma especialização'],
  c:1, e:'<strong>Entidade fraca</strong>. No relacional, a PK de DEPENDENTE incluirá a chave de EMPREGADO, formando chave composta.' },
{ id:'q1702', m:17, q:'Ainda neste DER, o que representa SUPERIDENT ligado ao próprio EMPREGADO?', img:'caso2-empregado-projeto-der.png',
  o:['Uma especialização','Um atributo multivalorado','Um auto-relacionamento (supervisão)','Uma agregação'],
  c:2, e:'É a assinatura do <strong>auto-relacionamento</strong>: o losango sai de EMPREGADO e volta para EMPREGADO. No esquema, isso aparece como a FK <code>SuperIdent</code> apontando para a própria tabela.' },
{ id:'q1703', m:17, q:'Neste DER do Engenho ABC, o que o triângulo entre FUNCIONARIO e ENGENHEIRO representa?', img:'caso3-engenho-abc-der.png',
  o:['Uma agregação','Uma especialização','Um relacionamento ternário','Uma entidade associativa'],
  c:1, e:'<strong>Especialização</strong>: o engenheiro <em>é um</em> funcionário, com CREA e ESPECIALIDADE como atributos próprios, herdando o CPF.' },
{ id:'q1704', m:17, q:'Ainda no Engenho ABC, o FONE do CLIENTE aparece em elipse dupla. O que isso significa no relacional?', img:'caso3-engenho-abc-der.png',
  o:['Vira colunas FONE1, FONE2','Vira a tabela CLIENTE_FONE(COD_CLI, FONE)','Vira chave primária do cliente','Vira um atributo composto'],
  c:1, e:'Elipse dupla = <strong>multivalorado</strong>, e multivalorado sempre vira <strong>tabela nova</strong> com a PK da entidade + o atributo.' },
{ id:'q1705', m:17, q:'No caso Casamento, PESSOA se liga a CASAMENTO por dois losangos (MARIDO e ESPOSA). Por quê?', img:'caso1-casamento-der.png',
  o:['Porque há duas entidades PESSOA diferentes','Porque PESSOA participa do casamento em dois papéis distintos','Porque a cardinalidade é N:N','Porque CASAMENTO é entidade fraca'],
  c:1, e:'Há <strong>um só</strong> retângulo PESSOA, com dois losangos voltando a ele — é um auto-relacionamento via CASAMENTO, expressando dois papéis.' },
{ id:'q1706', m:17, q:'As duas turmas resolveram o Casamento com cardinalidades diferentes (1:1 e N:1). O que fazer na prova?',
  o:['Só a 1:1 está certa','Só a N:1 está certa','As duas valem dentro das hipóteses adotadas — escreva a hipótese embaixo do desenho','Nenhuma vale; falta informação'],
  c:2, e:'O enunciado manda "adicionar as hipóteses que julgar necessárias". A leitura mais fiel ao mundo real é <strong>N:1</strong> (um local é nascimento de várias pessoas), mas declarar a hipótese é o que salva a questão.' },
{ id:'q1707', m:17, q:'Na engenharia reversa, uma tabela cuja PK começa com a PK de outra tabela indica:',
  o:['Um N:N resolvido','Uma possível entidade fraca','Um auto-relacionamento','Uma especialização'],
  c:1, e:'A chave transposta que <strong>entra na PK</strong> é a marca da entidade fraca. Se as duas colunas da PK fossem FKs para tabelas diferentes, aí sim seria um N:N resolvido.' },
{ id:'q1708', m:17, q:'No caso da planilha de Pedidos, SUB_TOTAL e TOTAL_PED aparecem como atributos. O que a normalização faria com eles?', img:'caso4-pedidos-der.png',
  o:['Transformaria em entidades','Removeria na 3FN, por serem valores calculados','Transformaria em chaves compostas','Manteria, por serem essenciais'],
  c:1, e:'<code>SUB_TOTAL = QTD × VL_PROD</code> e <code>TOTAL_PED</code> é a soma dos itens. Derivados armazenados são fonte de inconsistência — saem na <strong>3FN</strong>.' },
{ id:'q1709', m:17, q:'Duas turmas nomearam os losangos de forma diferente (TEM × POSSUIR, TRABALHA × TRABALHAR). O que a correção realmente procura?',
  o:['O nome exato dos relacionamentos','As cardinalidades, a entidade fraca, o auto-relacionamento e o N:N com atributo','O número de atributos por entidade','A posição dos retângulos no papel'],
  c:1, e:'O nome do losango é escolha de quem modela. O que <strong>não</strong> pode mudar é a estrutura.' },
{ id:'q1710', m:17, q:'Qual é o primeiro passo do roteiro para resolver qualquer exercício de MER/DER?',
  o:['Definir as cardinalidades','Ler o enunciado e marcar os substantivos','Escrever o CREATE TABLE','Procurar os casos especiais'],
  c:1, e:'Substantivos → candidatos a entidade. Depois vêm atributos, relacionamentos (verbos), cardinalidades, atributos do relacionamento, casos especiais e, por fim, o mapeamento.' }

];
