/* =========================================================================
   FLASHCARDS
   m = id do modulo · q = frente · a = verso (HTML) · hint = pista opcional
   ========================================================================= */

const CARDS = [

/* ── 1. Dado, Informação e Conhecimento ─────────────────────────────── */
{ id:'c101', m:1, q:'Qual é a cadeia que transforma dado em informação — e onde entra o conhecimento?', hint:'Três elementos e uma seta',
  a:'<p><code>DADO → PROCESSO DE TRANSFORMAÇÃO → INFORMAÇÃO</code></p><p>O <strong>conhecimento</strong> não está na linha: ele alimenta o processo por baixo. São as <strong>regras usadas para transformar</strong> o dado em informação.</p>' },
{ id:'c102', m:1, q:'O que é um DADO?',
  a:'<p>É o <strong>fato em sua forma primária (crua), sem contexto</strong>.</p><p>Exemplos: o número <code>8</code>, <code>R$ 1.000</code>, o nome de um empregado, a quantidade de peças em estoque.</p>' },
{ id:'c103', m:1, q:'O que é INFORMAÇÃO?',
  a:'<p>É o conjunto de dados <strong>organizados de uma forma que ganha valor além do fato em si</strong>.</p><p>"O total de vendas do mês foi R$ 250 mil" ajuda o gerente a decidir muito mais do que ver venda por venda solta.</p>' },
{ id:'c104', m:1, q:'O que é CONHECIMENTO?',
  a:'<p>É o corpo de <strong>regras, diretrizes e procedimentos</strong> usados para selecionar, organizar e manipular os dados, tornando-os úteis para uma tarefa específica.</p>' },
{ id:'c105', m:1, q:'A metáfora da carpintaria: o que é dado, conhecimento e informação?',
  a:'<ul><li><strong>Dado</strong> = a matéria-prima (madeira, prego, cola).</li><li><strong>Conhecimento</strong> = saber usar a serra e a furadeira.</li><li><strong>Informação</strong> = a cadeira pronta.</li></ul>' },
{ id:'c106', m:1, q:'De que depende o VALOR da informação?',
  a:'<p>De <strong>quanto ela ajuda alguém a tomar uma decisão</strong> e atingir metas.</p><p>Pode ser medido pelo tempo economizado numa decisão ou pelo aumento de lucro. Informação bonita que não ajuda a decidir nada tem pouco valor.</p>' },
{ id:'c107', m:1, q:'Cite as 9 características de uma boa informação.', hint:'Muito cobrado em prova',
  a:'<p><strong>Precisa · Completa · Econômica · Flexível · Confiável · Relevante · Simples · Em tempo · Verificável</strong></p>' },
{ id:'c108', m:1, q:'Um relatório chega com dados corretos, porém uma semana atrasado. Qual característica foi violada?',
  a:'<p><strong>Em tempo.</strong></p><p>Saber o tempo da semana passada não ajuda a decidir o casaco de hoje. Informação correta mas atrasada perde o valor.</p>' },
{ id:'c109', m:1, q:'O que significa "ELSL" e a qual característica está ligado?',
  a:'<p><strong>Entra Lixo, Sai Lixo.</strong> Ligado à característica <strong>Precisa</strong>: dado errado na entrada gera informação errada na saída.</p>' },
{ id:'c110', m:1, q:'Por que "mais dados" nem sempre significa melhor informação?',
  a:'<p>Excesso gera <strong>sobrecarga</strong> e piora a decisão — é a característica <strong>Simples</strong>. Informação demais e ninguém decide nada.</p>' },
{ id:'c111', m:1, q:'Diferença entre INFORMAÇÃO e CONHECIMENTO.',
  a:'<p>Informação é o <strong>resultado</strong>; conhecimento são as <strong>regras</strong> que produzem esse resultado.</p><p>Saber a fórmula da média é conhecimento. A média calculada é informação.</p>' },

/* ── 2. Sistemas e SI ───────────────────────────────────────────────── */
{ id:'c201', m:2, q:'O que é um SISTEMA?',
  a:'<p>Um conjunto de elementos/componentes que <strong>interagem para atingir um objetivo</strong>. Os elementos e as relações entre eles determinam como o sistema funciona.</p><p>Pode ser simples (assar um bolo) ou complexo (hospital, universidade, fábrica).</p>' },
{ id:'c202', m:2, q:'O que é um SISTEMA DE INFORMAÇÃO?',
  a:'<p>Um tipo <strong>especializado</strong> de sistema: componentes inter-relacionados que <strong>coletam</strong> (entrada), <strong>manipulam e armazenam</strong> (processamento) e <strong>disseminam</strong> (saída) dados, além de fornecer um mecanismo de <strong>feedback</strong>.</p>' },
{ id:'c203', m:2, q:'Quais são os 4 componentes de um Sistema de Informação?', hint:'O quarto é o mais esquecido',
  a:'<p><strong>Entrada → Processamento → Saída</strong>, mais o <strong>Feedback</strong>, que volta da saída para ajustar a entrada ou o processamento.</p>' },
{ id:'c204', m:2, q:'Para que serve o FEEDBACK num SI? Dê o exemplo do contracheque.',
  a:'<p>É a saída usada para <strong>ajustar</strong> a entrada ou o processamento.</p><p>Contracheque: entram as horas trabalhadas → calcula o salário → sai o contracheque. Se houver erro no valor, isso vira feedback para corrigir o dado de entrada.</p>' },
{ id:'c205', m:2, q:'Onde o banco de dados se encaixa dentro de um Sistema de Informação?',
  a:'<p>Ele é a <strong>camada de dados</strong>: o componente que armazena os dados e os devolve durante o processamento e a saída.</p>' },
{ id:'c206', m:2, q:'Todo sistema pode ser visto como qual esquema, e orientado por quê?',
  a:'<p><code>Entrada → Mecanismo de Processamento → Saída</code>, sempre orientado por uma <strong>meta</strong>.</p><p>Ex.: universidade — meta: aquisição de conhecimento; entradas: estudantes, professores, livros; processamento: ensino e pesquisa; saídas: formados e pesquisa.</p>' },

/* ── 3. BD e SGBD ───────────────────────────────────────────────────── */
{ id:'c301', m:3, q:'O que é um BANCO DE DADOS?',
  a:'<p>Um conjunto <strong>coerente e lógico de dados relacionados</strong> que possuem significado próprio (significância intrínseca), representam aspectos do <strong>mundo real</strong> e são mantidos para atender às necessidades da empresa, dispostos em uma ordem predefinida.</p>' },
{ id:'c302', m:3, q:'O que é um SGBD? Qual a sigla em inglês?',
  a:'<p><strong>Sistema Gerenciador de Banco de Dados</strong> — em inglês <strong>DBMS</strong> (Database Management System).</p><p>É uma <strong>coleção de programas</strong> que permite criar estruturas, manter dados e gerenciar as transações feitas nas tabelas, além de extrair informações de forma rápida e segura.</p>' },
{ id:'c303', m:3, q:'Diferença entre BANCO DE DADOS e SGBD.', hint:'Conteúdo × programa',
  a:'<p>O <strong>banco</strong> é o conjunto de dados — o "conteúdo". O <strong>SGBD</strong> é o software que gerencia esse conjunto.</p><p>Erro clássico: chamar MySQL ou Oracle de "banco de dados". Tecnicamente eles são <strong>SGBDs</strong>.</p>' },
{ id:'c304', m:3, q:'Um sistema de banco de dados tem que estrutura em duas partes?',
  a:'<ul><li><strong>Servidor (back end)</strong> — é o próprio SGBD. Cuida de manipulação de dados, segurança, definição de dados e integridade.</li><li><strong>Clientes (front ends)</strong> — as aplicações executadas sobre o SGBD, feitas por usuários, pelo fabricante ou por terceiros.</li></ul>' },
{ id:'c305', m:3, q:'Cite as 6 principais características de um SGBD.',
  a:'<p><strong>Controle de redundância · Compartilhamento de dados · Controle de acesso · Esquematização · Backup · Segurança</strong></p><p>Segurança é o fator que mais diferencia um banco de outro.</p>' },
{ id:'c306', m:3, q:'O que é a característica "esquematização" de um SGBD?',
  a:'<p>Os <strong>relacionamentos ficam armazenados no próprio banco</strong>, garantindo entendimento e integridade — não ficam só na cabeça de quem programou.</p>' },
{ id:'c307', m:3, q:'Quais são os 4 utilitários que ajudam o DBA?',
  a:'<ul><li><strong>Rotinas de carga</strong> — criam a versão inicial do banco a partir de arquivos.</li><li><strong>Descarregamento / recarregamento</strong> — backup e restauração.</li><li><strong>Reorganização</strong> — rearranja os dados, geralmente por desempenho.</li><li><strong>Rotinas estatísticas</strong> — tamanho de arquivos, distribuição de valores.</li></ul>' },
{ id:'c308', m:3, q:'O que faz o DBA?',
  a:'<p>O <strong>Administrador de Banco de Dados</strong> administra o banco: executa as rotinas utilitárias (carga, backup, reorganização, estatísticas) e cuida de desempenho, segurança e disponibilidade.</p>' },
{ id:'c309', m:3, q:'Qual o objetivo de um banco de dados relacional — e o que conta como "objeto"?',
  a:'<p>Armazenar um grupo de <strong>objetos</strong> de um dicionário de dados de forma a tornar rápida e segura a manipulação das informações.</p><p>"Objetos" inclui <strong>tabelas, visões (views), índices e até procedimentos e funções</strong> armazenados no banco.</p>' },
{ id:'c310', m:3, q:'Por que o compartilhamento de dados exige cuidado com concorrência?',
  a:'<p>Vários usuários acessando ao mesmo tempo podem gerar <strong>inconsistências</strong> — como duas reservas do mesmo assento. Por isso o SGBD precisa de controle de concorrência e atomicidade.</p>' },
{ id:'c311', m:3, q:'"O objetivo é sempre redundância zero." Certo ou errado?',
  a:'<p><strong>Errado.</strong> A característica é <strong>controle</strong> de redundância — mínimo necessário — e não a eliminação absoluta a qualquer custo.</p>' },

/* ── 4. Tipos de BD ─────────────────────────────────────────────────── */
{ id:'c401', m:4, q:'Quais são os 5 tipos de banco de dados vistos na aula?',
  a:'<p><strong>Hierárquico · Rede · Relacional · Objeto-Relacional · Objeto</strong></p>' },
{ id:'c402', m:4, q:'Como o modelo HIERÁRQUICO representa os dados?',
  a:'<p>Como uma <strong>árvore</strong> — uma hierarquia de registros em que cada filho tem <strong>um único pai</strong>.</p><p>Exemplo do mundo real: a estrutura de pastas do sistema operacional.</p>' },
{ id:'c403', m:4, q:'Como o modelo REDE representa os dados, e por que é chamado de generalização do hierárquico?',
  a:'<p>Registros <strong>vinculados uns aos outros</strong> formando conjuntos. É generalização porque aqui um filho <strong>pode ter mais de um pai</strong>.</p><p>Ex.: um funcionário que participa de vários projetos e cada projeto tem vários funcionários.</p>' },
{ id:'c404', m:4, q:'A diferença-chave entre hierárquico e rede é...', hint:'Uma pergunta só',
  a:'<p><strong>Quantos pais um registro pode ter.</strong> Hierárquico: 1. Rede: vários.</p>' },
{ id:'c405', m:4, q:'Como o modelo RELACIONAL representa os dados?',
  a:'<p>Como uma coleção simples de <strong>linhas e colunas</strong> em tabelas bidimensionais. Linhas são <strong>tuplas</strong>, colunas são <strong>atributos</strong>, e os relacionamentos são feitos por <strong>chaves</strong>. É o mais utilizado.</p>' },
{ id:'c406', m:4, q:'De onde vem o nome "relacional"?',
  a:'<p>Do termo matemático <strong>relação</strong>, que é o nome formal de uma tabela — <em>não</em> de "ter relacionamentos".</p><p>Todos os modelos têm relações entre dados; o relacional é o que as organiza em relações no sentido matemático.</p>' },
{ id:'c407', m:4, q:'O que caracteriza o modelo OBJETO-RELACIONAL e o modelo OBJETO?',
  a:'<ul><li><strong>Objeto-Relacional:</strong> combina o modelo orientado a objetos (propriedades + métodos) com o relacional (linhas e colunas).</li><li><strong>Objeto:</strong> representa <strong>dados e processos em um único objeto</strong>.</li></ul>' },

/* ── 5. Arquiteturas ────────────────────────────────────────────────── */
{ id:'c501', m:5, q:'Cite as 5 arquiteturas de processamento, na ordem histórica.',
  a:'<p><strong>Centralizado → Cliente/Servidor (2 camadas) → 3 camadas → 4 camadas → Distribuído</strong></p>' },
{ id:'c502', m:5, q:'Processamento centralizado: como funciona e qual o problema?',
  a:'<p>Uma <strong>única máquina</strong> faz tudo — a era dos <strong>mainframes</strong>. Aplicação e dados num só lugar; as estações não tinham poder de processamento.</p><p><strong>Problema:</strong> custo altíssimo de hardware.</p>' },
{ id:'c503', m:5, q:'Cliente/Servidor (2 camadas): qual era o objetivo e qual o problema?',
  a:'<p><strong>Objetivo:</strong> descentralizar o processamento. Cliente fica com apresentação <em>e</em> lógica de negócio; servidor fica com o banco.</p><p><strong>Problema:</strong> atualizar o aplicativo em <strong>cada estação</strong> — imagine 1000 máquinas manualmente.</p>' },
{ id:'c504', m:5, q:'O que o modelo de 3 CAMADAS tira do cliente, e qual a vantagem?',
  a:'<p>Tira a <strong>regra de negócio</strong> e centraliza num <strong>servidor de aplicação</strong>. Fica: apresentação no cliente, lógica no servidor de aplicação, dados no servidor de banco.</p><p><strong>Vantagem:</strong> atualizar num único ponto, sem trocar executável em todas as estações.</p>' },
{ id:'c505', m:5, q:'O que o modelo de 4 CAMADAS tira do cliente, além da regra de negócio?',
  a:'<p>Tira também a <strong>apresentação</strong>, centralizando num <strong>servidor web</strong> (IIS, Apache). O acesso passa a ser por <strong>browser</strong>.</p><p>Camadas: cliente (browser) → apresentação (servidor web) → lógica → dados.</p>' },
{ id:'c506', m:5, q:'Qual a diferença central entre 3 e 4 camadas?', hint:'O que sai do cliente',
  a:'<p>A de 4 camadas <strong>também tira a apresentação</strong> do cliente, que vai para o servidor web, e o acesso passa a ser via browser. Na de 3, a apresentação ainda roda no cliente.</p>' },
{ id:'c507', m:5, q:'O que é processamento distribuído?',
  a:'<p>Máquinas diferentes conectadas em rede de modo que <strong>uma única tarefa de processamento se estende por várias máquinas</strong>. A comunicação é feita por software de gerenciamento de rede.</p>' },
{ id:'c508', m:5, q:'Qual o cuidado ao adotar 3 ou mais camadas?',
  a:'<p><strong>Desempenho e dimensionamento dos servidores.</strong> Ao centralizar serviços, processamento e memória tornam-se críticos.</p>' },
{ id:'c509', m:5, q:'"3 camadas significa 3 máquinas físicas." Certo ou errado?',
  a:'<p><strong>Errado.</strong> São <strong>camadas lógicas</strong> — apresentação, lógica e dados — que <em>podem</em> estar em servidores diferentes, mas não obrigatoriamente.</p>' },

/* ── 6. Visão geral da modelagem ────────────────────────────────────── */
{ id:'c601', m:6, q:'Quais são as 4 etapas da modelagem, do enunciado ao banco rodando?',
  a:'<p><code>ENUNCIADO → MER → DER → MODELO RELACIONAL → MODELO FÍSICO</code></p><p>MER é o conceitual (as ideias), DER é o desenho, relacional são as tabelas, físico é a implementação no SGBD.</p>' },
{ id:'c602', m:6, q:'Diferença entre MER e DER.',
  a:'<p>O <strong>MER</strong> é o modelo — o conjunto de ideias e decisões. O <strong>DER</strong> é a <strong>representação gráfica</strong> desse modelo, com os símbolos padrão.</p><p>Muita gente usa como sinônimo, mas o DER é o desenho do MER.</p>' },
{ id:'c603', m:6, q:'Por que o MER é considerado "universal"?',
  a:'<p>Porque descreve o <strong>negócio</strong>, não um produto. Ele não está preso a nenhum SGBD específico e pode ser implementado em qualquer um.</p>' },
{ id:'c604', m:6, q:'Conceitual, lógico e físico: qual pergunta cada um responde?',
  a:'<ul><li><strong>Conceitual</strong> (MER/DER) = <em>o quê</em>.</li><li><strong>Lógico</strong> (relacional) = <em>como em tabelas</em>.</li><li><strong>Físico</strong> = <em>como neste SGBD</em> (tipos, CREATE TABLE, índices, constraints).</li></ul>' },
{ id:'c605', m:6, q:'Quais são os DOIS problemas centrais que a modelagem busca evitar?',
  a:'<ul><li><strong>Redundância (repetição)</strong> — com duas cópias da informação, nunca se sabe em qual confiar.</li><li><strong>Desperdício de espaço</strong> — repetir nomes, descrições e datas.</li></ul><p>A solução é isolar informações em tabelas distintas e ligá-las por um <strong>código comum</strong>.</p>' },
{ id:'c606', m:6, q:'Símbolos do DER: retângulo, retângulo duplo e losango.',
  a:'<ul><li><strong>Retângulo</strong> — entidade</li><li><strong>Retângulo duplo</strong> — entidade fraca</li><li><strong>Losango</strong> — relacionamento</li></ul>' },
{ id:'c607', m:6, q:'Símbolos do DER: elipse, elipse sublinhada, elipse dupla e triângulo.',
  a:'<ul><li><strong>Elipse</strong> — atributo</li><li><strong>Elipse sublinhada</strong> — atributo-chave (PK)</li><li><strong>Elipse dupla</strong> — atributo multivalorado</li><li><strong>Triângulo</strong> — especialização / generalização</li></ul>' },
{ id:'c608', m:6, q:'Cite as vantagens do MER.',
  a:'<p>Sintaxe robusta (documenta com precisão) · comunicação fácil com o usuário · facilidade de criar e manter · integração entre aplicações · <strong>utilização universal</strong> (independe do SGBD).</p>' },
{ id:'c609', m:6, q:'O que acontece com os losangos quando o MER vira Modelo Relacional?',
  a:'<p>Eles <strong>somem</strong>. Relacionamentos viram <strong>FK</strong> (nos casos 1:N e 1:1) ou <strong>tabelas</strong> (no caso N:N).</p><p>Tratar MER e Modelo Relacional como a mesma coisa é um erro clássico.</p>' },

/* ── 7. Entidades e Atributos ───────────────────────────────────────── */
{ id:'c701', m:7, q:'O que é uma ENTIDADE — e no que ela vira no banco?',
  a:'<p>Um agrupamento lógico de informações inter-relacionadas sobre o qual precisamos guardar dados. É "tudo aquilo que pode ser individualizado e tem existência própria", física ou abstrata.</p><p>No modelo físico, vira uma <strong>tabela</strong>.</p>' },
{ id:'c702', m:7, q:'O que é um ATRIBUTO e o que é uma TUPLA?',
  a:'<ul><li><strong>Atributo</strong> — característica/propriedade da entidade. No banco vira <strong>coluna</strong>.</li><li><strong>Tupla</strong> — uma <strong>linha/registro</strong> da tabela.</li></ul>' },
{ id:'c703', m:7, q:'Qual a regra prática para achar entidades e relacionamentos num enunciado?',
  a:'<p>Examine os <strong>substantivos</strong> — costumam ser entidades. Os <strong>verbos</strong> costumam ser relacionamentos.</p>' },
{ id:'c704', m:7, q:'Qual o número mínimo de atributos para justificar uma entidade — e o que fazer se tiver menos?',
  a:'<p>No mínimo <strong>dois</strong>. Uma entidade com um único atributo normalmente será <strong>agregada</strong> a outra.</p>' },
{ id:'c705', m:7, q:'O que é um Conjunto de Entidades (CE)?',
  a:'<p>O conjunto de <strong>todas as ocorrências</strong> de uma entidade. Seus elementos são <strong>distintos</strong> — a lista de atributos precisa ser suficiente para caracterizar cada ocorrência.</p>' },
{ id:'c706', m:7, q:'Diferença entre ENTIDADE e INSTÂNCIA.',
  a:'<p>A entidade é a <strong>classe/categoria</strong> — por exemplo <code>CD</code>. A instância é um objeto específico — o CD "Mais do Mesmo".</p>' },
{ id:'c707', m:7, q:'Quais são os 3 tipos de atributo?',
  a:'<ul><li><strong>Simples</strong> — um único valor (nome, salário).</li><li><strong>Composto</strong> — contém subatributos (endereço = rua, número, complemento, cidade, CEP).</li><li><strong>Multivalorado</strong> — vários valores para a mesma entidade (vários telefones).</li></ul>' },
{ id:'c708', m:7, q:'Atributo COMPOSTO × MULTIVALORADO: qual a diferença?', hint:'Um valor dividido × vários valores',
  a:'<p><strong>Composto</strong> = <em>um</em> valor dividido em partes (endereço). Ao virar tabela, "achata-se" em colunas.</p><p><strong>Multivalorado</strong> = <em>vários</em> valores do mesmo tipo (telefones). Vira uma tabela nova.</p>' },
{ id:'c709', m:7, q:'Como se indica um atributo multivalorado — na notação textual e no DER?',
  a:'<p>Na notação textual, com <strong><code>*</code> após o nome</strong>: <code>Funcionario(numf, nome, telefone*)</code>.</p><p>No DER, com <strong>elipse dupla</strong>.</p>' },
{ id:'c710', m:7, q:'Por que guardar telefones como FONE1, FONE2, FONE3 está errado?',
  a:'<p>Porque é rígido (limita a 3), desperdiça espaço e dificulta consultas. A modelagem correta é <strong>criar uma tabela</strong> para os telefones:</p><div class="pre">CLIENTE(cod_cli PK, nome)\nCLIENTE_FONE(cod_cli PK/FK, fone PK)</div>' },
{ id:'c711', m:7, q:'Como se classificam as entidades quanto à origem?',
  a:'<ul><li><strong>Fundamental</strong> — contém dados básicos, resultado ou alimentador das operações da empresa (CLIENTE, PROJETO, FUNCIONÁRIO). Tem <strong>existência própria</strong>.</li><li><strong>Associativa</strong> — formada pelo <strong>relacionamento de duas entidades fundamentais</strong> (pedido × produto).</li></ul>' },
{ id:'c712', m:7, q:'Quando algo é entidade e quando é só atributo?',
  a:'<p>Se tem <strong>características próprias e várias ocorrências</strong>, é entidade. Se apenas <strong>descreve</strong> algo, é atributo.</p><p>Erro clássico: criar uma entidade "Cor" para a cor de um produto quando basta um atributo.</p>' },

/* ── 8. Chaves ──────────────────────────────────────────────────────── */
{ id:'c801', m:8, q:'O que é uma CHAVE PRIMÁRIA e quais as 3 exigências do seu conteúdo?',
  a:'<p>Identifica <strong>unicamente</strong> cada ocorrência (tupla) de uma entidade. Todos os demais atributos dependem dela.</p><p>Seu conteúdo deve ser <strong>único, exclusivo e imutável</strong>.</p>' },
{ id:'c802', m:8, q:'O que é uma CHAVE ESTRANGEIRA?',
  a:'<p>Atributo que estabelece a relação com a <strong>PK de outra entidade</strong>, permitindo o relacionamento. Ocorre quando uma entidade "herda" a chave de outra para se ligar a ela.</p>' },
{ id:'c803', m:8, q:'O que é uma CHAVE SECUNDÁRIA?',
  a:'<p>Usada para <strong>classificação e pesquisa</strong> — buscas em ordem crescente/decrescente por data, valor, status.</p><p><strong>Não identifica unicamente.</strong> Serve para consultar e ordenar.</p>' },
{ id:'c804', m:8, q:'Os macetes: qual pergunta a PK responde e qual a FK responde?',
  a:'<p><strong>PK:</strong> "quem sou eu?" — identifica o registro dentro da própria tabela.</p><p><strong>FK:</strong> "de quem eu dependo / quem eu referencio?" — aponta para a PK de outra tabela.</p>' },
{ id:'c805', m:8, q:'O que é uma CHAVE COMPOSTA (ou concatenada)?',
  a:'<p>Uma PK formada por <strong>mais de um atributo</strong>. É a <strong>união</strong> dos atributos que garante o acesso a uma única linha.</p><p>Ex.: <code>ITENS_PEDIDO</code> com PK = <code>NR_PEDIDO + ITEM</code>.</p>' },
{ id:'c806', m:8, q:'Por que a PK de ITENS_PEDIDO precisa ser NR_PEDIDO + ITEM e não só NR_PEDIDO?',
  a:'<p>Porque o mesmo <code>NR_PEDIDO</code> tem <strong>vários itens</strong>. Só a combinação identifica uma linha.</p><p>Achar que um dos atributos sozinho identifica é o erro clássico da chave composta.</p>' },
{ id:'c807', m:8, q:'Por que "nome" costuma ser uma PK ruim?',
  a:'<p>Porque pode <strong>repetir</strong> e pode <strong>mudar</strong> — viola as exigências de unicidade e imutabilidade.</p>' },
{ id:'c808', m:8, q:'E se não existir um atributo natural que sirva de PK?',
  a:'<p><strong>Crie um</strong> — por exemplo um código sequencial. Nem todo campo é boa chave.</p>' },
{ id:'c809', m:8, q:'Um mesmo atributo pode ser PK e FK ao mesmo tempo?',
  a:'<p><strong>Sim.</strong> Acontece em <strong>entidades fracas</strong> e em <strong>tabelas associativas</strong>.</p><p>Ex.: <code>CLIENTE_FONE(COD_CLI [PK/FK], FONE [PK])</code> — <code>COD_CLI</code> compõe a PK e referencia <code>CLIENTE</code>.</p>' },
{ id:'c810', m:8, q:'Chave SECUNDÁRIA × chave ESTRANGEIRA: qual o propósito de cada uma?',
  a:'<p><strong>Secundária</strong> serve para <strong>busca e ordenação</strong>. <strong>Estrangeira</strong> serve para <strong>ligar tabelas</strong>, referenciando a PK de outra.</p><p>Confundir as duas é erro comum.</p>' },
{ id:'c811', m:8, q:'Como o atributo-chave aparece no DER?',
  a:'<p><strong>Sublinhado</strong> — a elipse sublinhada.</p>' },

/* ── 9. Relacionamentos e Cardinalidade ─────────────────────────────── */
{ id:'c901', m:9, q:'O que é um RELACIONAMENTO e como aparece no DER?',
  a:'<p>A <strong>associação entre entidades</strong>. Sempre que duas entidades têm interdependência, existe um relacionamento — normalmente um <strong>verbo</strong> (solicita, contém, gerencia).</p><p>No DER é um <strong>losango</strong>.</p>' },
{ id:'c902', m:9, q:'O que é CARDINALIDADE?',
  a:'<p>Indica <strong>quantas ocorrências</strong> de uma entidade podem se relacionar com ocorrências de outra. É o "quantos de cada lado?".</p><p>As três: <strong>1:1, 1:N e N:N</strong>.</p>' },
{ id:'c903', m:9, q:'Quais são os TRÊS elementos de um relacionamento?',
  a:'<p>Um <strong>nome</strong> (verbo), a <strong>opcionalidade</strong> (deve/pode) e a <strong>cardinalidade</strong> (uma única / uma ou mais).</p>' },
{ id:'c904', m:9, q:'Ao encontrar um relacionamento 1:1, quais DUAS perguntas você deve fazer?', hint:'Dica do professor',
  a:'<p>1. "Essas duas entidades não deveriam ser uma <strong>entidade só</strong>?"</p><p>2. "E amanhã, isso não pode virar <strong>1:N</strong>?"</p>' },
{ id:'c905', m:9, q:'No relacionamento 1:N, onde ficam os dados básicos e para onde vai a FK?',
  a:'<p>O lado <strong>1</strong> tem os dados básicos. A FK vai para o lado <strong>N</strong>.</p><p>Ex.: <code>DEPARTAMENTO 1 — N FUNCIONARIO</code> → <code>funcionario.cod_depto</code> é FK.</p>' },
{ id:'c906', m:9, q:'Por que um relacionamento N:N não pode ser implementado diretamente numa tabela?',
  a:'<p>Porque numa tabela cada linha tem <strong>um valor por coluna</strong> — não há como representar as múltiplas combinações dos dois lados.</p><p>Ele é transformado em <strong>dois relacionamentos 1:N</strong> com uma <strong>entidade associativa</strong> no meio.</p>' },
{ id:'c907', m:9, q:'Classifique a cardinalidade: (a) pessoa e CPF (b) turma e aluno (c) produto e fornecedor.',
  a:'<p>(a) <strong>1:1</strong> · (b) <strong>1:N</strong> · (c) <strong>N:N</strong></p>' },
{ id:'c908', m:9, q:'Dê dois exemplos clássicos de cada cardinalidade.',
  a:'<ul><li><strong>1:1</strong> — departamento e gerente; placa-mãe e computador.</li><li><strong>1:N</strong> — cliente e pedido; pedido e item do pedido.</li><li><strong>N:N</strong> — autor e livro; aluno e disciplina; produto e fornecedor.</li></ul>' },
{ id:'c909', m:9, q:'Qual erro no 1:N quebra o modelo relacional inteiro?',
  a:'<p><strong>Inverter o lado da FK.</strong> Ela vai no lado <strong>N</strong>, nunca no lado 1.</p>' },
{ id:'c910', m:9, q:'Por que a cardinalidade é tão importante para o mapeamento?',
  a:'<p>Porque ela <strong>determina como o relacionamento vira tabela</strong>: 1:N coloca uma FK no lado N; N:N cria uma tabela associativa. Errar a cardinalidade quebra o modelo relacional inteiro.</p>' },

/* ── 10. Grau e Auto-relacionamento ─────────────────────────────────── */
{ id:'c1001', m:10, q:'O que é o GRAU de um relacionamento?',
  a:'<p><strong>Quantas entidades participam</strong> dele.</p><p>Grau 1 = unário (auto-relacionamento) · Grau 2 = binário (o mais comum) · Grau 3 = ternário · Grau 4+.</p>' },
{ id:'c1002', m:10, q:'CARDINALIDADE × GRAU: qual pergunta cada um responde?', hint:'Pega-ratão clássico',
  a:'<p><strong>Cardinalidade</strong> = "quantos de cada lado?" (1:1, 1:N, N:N).</p><p><strong>Grau</strong> = "quantas entidades participam?" (1, 2, 3...).</p><p>São perguntas diferentes. Um auto-relacionamento é grau 1 e <em>ainda assim</em> tem cardinalidade.</p>' },
{ id:'c1003', m:10, q:'O que é auto-relacionamento e o que se usa nas ligações?',
  a:'<p>É quando <strong>uma entidade se relaciona com ela mesma</strong> (grau 1 / unário).</p><p>Usam-se <strong>rótulos de papel</strong> nas ligações para explicitar o papel — ex.: "é componente de" / "tem como componente".</p>' },
{ id:'c1004', m:10, q:'Dê exemplos clássicos de auto-relacionamento.',
  a:'<ul><li><code>FUNCIONARIO — supervisiona — FUNCIONARIO</code> (1:N)</li><li>Pessoa é pai/mãe de pessoa</li><li>Categoria possui subcategoria</li><li>Peça é componente de peça (N:N, com atributo <code>quantidade</code>)</li></ul>' },
{ id:'c1005', m:10, q:'Por que NÃO criar uma entidade "Supervisor" separada?',
  a:'<p>Porque o supervisor <strong>é</strong> um funcionário. Criar uma entidade separada duplicaria a entidade. Use <strong>auto-relacionamento</strong>.</p>' },
{ id:'c1006', m:10, q:'"Auto-relacionamento é grau 2 porque Funcionário aparece duas vezes." Certo ou errado?',
  a:'<p><strong>Errado.</strong> É <strong>grau 1</strong> — há uma <em>única</em> entidade participando, mesmo que ela apareça nas duas pontas do losango.</p>' },
{ id:'c1007', m:10, q:'Ao ler um conjunto de tabelas, como você identifica um auto-relacionamento?',
  a:'<p>Uma <strong>FK que aponta para a própria tabela</strong>.</p><div class="pre">CREATE TABLE empregado (\n    ident       INTEGER PRIMARY KEY,\n    nome        VARCHAR(100),\n    super_ident INTEGER REFERENCES empregado\n);</div>' },
{ id:'c1008', m:10, q:'O que é um relacionamento ternário e quando ele deve virar agregação?',
  a:'<p><strong>Três entidades num mesmo losango.</strong> Ex.: Professor–Aluno–Disciplina (cardinalidade tipo 1:N:N), ou Materiais–Pedidos–Requisições (MRP).</p><p>Quando o ternário fica <strong>artificial</strong>, a solução costuma ser <strong>agregação</strong>.</p>' },

/* ── 11. Entidade fraca e associativa ───────────────────────────────── */
{ id:'c1101', m:11, q:'O que é uma ENTIDADE FRACA e como aparece no DER?',
  a:'<p>Uma entidade que <strong>depende de outra para existir/ser identificada</strong>. Sua identificação isolada não é suficiente — ela precisa da chave da entidade forte.</p><p>No DER, é um <strong>retângulo duplo</strong>.</p>' },
{ id:'c1102', m:11, q:'Por que DEPENDENTE é entidade fraca — e o que isso implica na PK?',
  a:'<p>Dois funcionários podem ter um dependente chamado "Pedro"; só o nome não identifica.</p><p>No relacional, a tabela da fraca recebe a <strong>PK da forte como parte da sua própria PK</strong> — chave composta.</p><div class="pre">DEPENDENTE(ident_emp PK/FK, nome PK, sexo, datanasc, parentesco)</div>' },
{ id:'c1103', m:11, q:'Como se chama o relacionamento que liga a entidade fraca à forte?',
  a:'<p><strong>Relacionamento identificador.</strong></p>' },
{ id:'c1104', m:11, q:'O que é uma ENTIDADE ASSOCIATIVA?',
  a:'<p>Uma estrutura que representa a <strong>associação entre duas entidades fundamentais</strong>, especialmente em relacionamentos <strong>N:N</strong>.</p><p>Surge ao transformar um N:N em dois 1:N. É formada pela <strong>união das PKs</strong> das entidades envolvidas.</p>' },
{ id:'c1105', m:11, q:'O que é uma entidade associativa ATRIBUTIVA?',
  a:'<p>Aquela que carrega <strong>atributos próprios do relacionamento</strong> — que não pertencem a nenhuma das entidades.</p><p>Ex.: <code>MATERIAL N — FORNECE — N FORNECEDOR</code> com <code>prazo, preço, quantidade</code>: esses atributos pertencem ao <em>fornecimento</em>.</p>' },
{ id:'c1106', m:11, q:'ENTIDADE FRACA × ENTIDADE ASSOCIATIVA: as duas se parecem. Qual a diferença real?', hint:'A motivação',
  a:'<p>A <strong>fraca</strong> existe por <strong>dependência de existência</strong> (o dependente não existe sem o funcionário).</p><p>A <strong>associativa</strong> nasce para <strong>resolver um N:N</strong> ou guardar atributos do relacionamento.</p><p>Podem coincidir na aparência — retângulo duplo, chave composta — mas a motivação é diferente.</p>' },
{ id:'c1107', m:11, q:'O atributo HORAS de TrabalhaNo pertence ao empregado, ao projeto ou ao relacionamento?',
  a:'<p>Ao <strong>relacionamento</strong>. <code>horas</code> depende da combinação empregado + projeto, não de um dos dois isoladamente.</p><div class="pre">trabalha_no(ident_emp PK/FK, proj_num PK/FK, horas)</div>' },
{ id:'c1108', m:11, q:'O que é tabela mestre e tabela detalhe?',
  a:'<p>A <strong>mestre</strong> tem os dados principais (lado 1). A <strong>detalhe</strong> (lado N / associativa) depende dela.</p>' },
{ id:'c1109', m:11, q:'Ao ver uma tabela intermediária com duas FKs, o que você conclui?',
  a:'<p>Que é quase sempre um <strong>N:N resolvido</strong> — uma entidade associativa.</p>' },
{ id:'c1110', m:11, q:'Transforme ALUNO N—N DISCIPLINA (com atributo nota) em associativa completa.',
  a:'<div class="pre">ALUNO_DISCIPLINA(cod_aluno, cod_disciplina, nota)\nPK = (cod_aluno, cod_disciplina)\ncod_aluno      → FK para ALUNO\ncod_disciplina → FK para DISCIPLINA</div><p>A <code>nota</code> é atributo do relacionamento — por isso mora aqui.</p>' },

/* ── 12. Especialização, Generalização, Agregação ───────────────────── */
{ id:'c1201', m:12, q:'O que é ESPECIALIZAÇÃO e de onde vem a ideia?',
  a:'<p>Partir de uma entidade <strong>geral</strong> e criar entidades <strong>mais específicas</strong>. Vem da ideia de <strong>subclasse e herança</strong> da orientação a objetos — a relação <strong>"é-um"</strong>.</p><p>No DER, usa o <strong>triângulo</strong>.</p>' },
{ id:'c1202', m:12, q:'Especialização × Generalização: qual a diferença?',
  a:'<p>Mesmo relacionamento, direções opostas.</p><ul><li><strong>Especialização</strong> = geral → específico (top-down).</li><li><strong>Generalização</strong> = específicos → geral (bottom-up).</li></ul>' },
{ id:'c1203', m:12, q:'O que o símbolo "+" indica numa especialização?',
  a:'<p>Especialização <strong>exclusiva</strong> ("ou exclusivo"): a entidade pertence a <strong>apenas um</strong> subconjunto.</p>' },
{ id:'c1204', m:12, q:'"É-UM" × "TEM-UM": qual é qual?',
  a:'<p><strong>É-um</strong> = especialização. Uma secretária <em>é uma</em> funcionária, com todos os atributos de funcionário mais os próprios.</p><p><strong>Tem-um</strong> = relacionamento comum. Um funcionário <em>tem um</em> departamento.</p>' },
{ id:'c1205', m:12, q:'O que é AGREGAÇÃO?',
  a:'<p>Tratar um <strong>relacionamento como se fosse uma entidade</strong>, para que ele possa participar de <strong>outro</strong> relacionamento.</p><p>Ex.: <code>MEDICO — ATENDE — PACIENTE</code> e depois <code>HOSPITAL — ACOMPANHA — [MEDICO ATENDE PACIENTE]</code>.</p>' },
{ id:'c1206', m:12, q:'Quando a agregação é preferível a um relacionamento ternário?',
  a:'<p>Quando o ternário fica <strong>artificial</strong> e um relacionamento precisa participar de outro.</p><p>Ex. do slide: em vez do ternário MRP (Materiais, Requisições, Pedidos), separa-se em "Itens de requisição" agregado e "Itens de pedido" ligando a Pedidos.</p>' },
{ id:'c1207', m:12, q:'AGREGAÇÃO × ENTIDADE ASSOCIATIVA: as duas transformam relacionamento em algo que se relaciona. Diferença?',
  a:'<p>A <strong>associativa</strong> resolve um <strong>N:N entre duas entidades</strong>.</p><p>A <strong>agregação</strong> empacota um relacionamento para ligá-lo a uma <strong>terceira</strong> entidade.</p>' },
{ id:'c1208', m:12, q:'Como fica a especialização no relacional? Escreva FUNCIONARIO → ENGENHEIRO.',
  a:'<div class="pre">FUNCIONARIO(cpf PK, nome, salario)\nENGENHEIRO(cpf PK/FK → FUNCIONARIO, crea, especialidade)</div><p>O <code>cpf</code> do engenheiro é <strong>PK e FK ao mesmo tempo</strong> — é assim que a chave é herdada.</p>' },
{ id:'c1209', m:12, q:'Qual erro clássico ao modelar especialização?',
  a:'<p><strong>Repetir os atributos do "pai" em cada especialização</strong> em vez de herdá-los.</p>' },

/* ── 13. Integridade referencial ────────────────────────────────────── */
{ id:'c1301', m:13, q:'O que é INTEGRIDADE REFERENCIAL?',
  a:'<p>A regra que garante que <strong>toda FK aponte para um registro que realmente existe</strong> na tabela referenciada. É o mecanismo que mantém a consistência das informações gravadas.</p>' },
{ id:'c1302', m:13, q:'O que o SGBD impede, em nome da integridade referencial?',
  a:'<p>Qualquer <strong>inclusão, exclusão ou alteração</strong> que deixe uma FK sem correspondente na PK da outra tabela.</p><p>Também não permite valores duplicados onde deve haver unicidade, nem referência a chave inválida.</p>' },
{ id:'c1303', m:13, q:'O que pode acontecer ao excluir um registro pai que tem filhos referenciando-o?',
  a:'<p>Duas estratégias:</p><ul><li><strong>Bloquear</strong> (<code>RESTRICT</code>) — o SGBD impede a exclusão.</li><li><strong>Cascata</strong> (<code>CASCADE</code>) — apaga ou altera os dependentes junto.</li></ul>' },
{ id:'c1304', m:13, q:'Integridade REFERENCIAL × integridade de ENTIDADE.',
  a:'<p><strong>Referencial</strong> cuida da <strong>FK</strong> — referências válidas entre tabelas.</p><p><strong>De entidade</strong> cuida da <strong>PK</strong> — identificador único e não nulo.</p><p>São regras complementares.</p>' },
{ id:'c1305', m:13, q:'Dado CLIENTE com cod_cli 1 e 2, e PEDIDOs com cod_cli 1, 2 e 5 — qual viola a integridade?',
  a:'<p>O pedido com <code>cod_cli = 5</code>: <strong>não existe cliente 5</strong>. É uma referência quebrada — um registro órfão.</p>' },
{ id:'c1306', m:13, q:'"Integridade referencial é automática." Certo ou errado?',
  a:'<p><strong>Errado.</strong> Ela precisa ser <strong>declarada</strong> — via FK e constraints — no modelo físico.</p><div class="pre">FOREIGN KEY (cod_cli) REFERENCES cliente(cod_cli)\n    ON DELETE CASCADE</div>' },

/* ── 14. Mapeamento ─────────────────────────────────────────────────── */
{ id:'c1401', m:14, q:'Regra 1: entidade forte e entidade fraca viram o quê?',
  a:'<p><strong>Forte:</strong> tabela com seus próprios atributos. Ex.: <code>Contas(numero, saldo)</code>.</p><p><strong>Fraca:</strong> tabela com a <strong>PK da entidade forte + seus atributos próprios</strong>. A chave transposta <strong>compõe a PK</strong>. Ex.: <code>Reparos(chassi, data, tipo, valor)</code>.</p>' },
{ id:'c1402', m:14, q:'Regra 3: o que acontece com um relacionamento 1:N no mapeamento?',
  a:'<p><strong>NÃO gera tabela.</strong> Transpõe-se a chave do lado <strong>1</strong> para o lado <strong>N</strong>, virando <strong>FK</strong>.</p><p>Essa FK <strong>não</strong> faz parte da PK do lado N.</p><p><em>Obs.: um 1:N pode gerar tabela quando não há totalidade na associação.</em></p>' },
{ id:'c1403', m:14, q:'Regra 4: o que acontece com um relacionamento N:N?',
  a:'<p><strong>Gera uma tabela associativa</strong> com as <strong>PKs das entidades envolvidas</strong> mais os <strong>atributos próprios do relacionamento</strong>.</p><p>Ex.: <code>Emprestimos(COD_usuario, No_tombo, data_ret, data_dev)</code>.</p>' },
{ id:'c1404', m:14, q:'Regra 5: num relacionamento 1:1, como decidir para onde vai a chave?',
  a:'<p>Observe a <strong>participação total</strong>. A chave vai para o lado com participação total.</p><p>Ex.: "todo país tem uma capital, mas nem toda cidade é capital" → a tabela <strong>Países</strong> recebe <code>codigo_capital</code>.</p>' },
{ id:'c1405', m:14, q:'Regra 6: como se mapeia um atributo multivalorado?',
  a:'<p>Cria-se uma <strong>tabela nova</strong> com o atributo + a <strong>PK da entidade</strong> que o possui.</p><p>Ex.: <code>Livros(No_tombo, ...)</code> e <code>Autores(No_tombo, autor)</code>.</p>' },
{ id:'c1406', m:14, q:'Regra 7: quais são as duas formas de mapear especialização — e quando a segunda é permitida?',
  a:'<p><strong>Forma 1</strong> (sempre válida): tabela do nível mais alto + uma por especialização.</p><div class="pre">Contas(numero, saldo)\nContas_corrente(numero, limite)\nContas_poupanca(numero, data_base)</div><p><strong>Forma 2</strong>: só as tabelas dos níveis mais baixos, com os atributos herdados. <strong>Só é permitida</strong> se a especialização for <strong>mutuamente exclusiva e total</strong>.</p>' },
{ id:'c1407', m:14, q:'Chave transposta num 1:N comum × numa entidade fraca: qual a diferença?', hint:'A PK',
  a:'<p>No <strong>1:N comum</strong>, a chave transposta é <strong>só FK</strong> — fica fora da PK.</p><p>Na <strong>entidade fraca</strong>, a chave transposta <strong>entra na PK</strong>, formando chave composta.</p>' },
{ id:'c1408', m:14, q:'Por que 1:N não gera tabela mas N:N gera?',
  a:'<p>No 1:N a <strong>FK resolve tudo</strong>: cada linha do lado N aponta para uma única linha do lado 1.</p><p>No N:N não cabe numa tabela só — é preciso uma associativa com as duas chaves para representar as combinações.</p>' },
{ id:'c1409', m:14, q:'Cite os 4 erros mais comuns no mapeamento.',
  a:'<ul><li>Criar tabela para relacionamento 1:N (basta a FK).</li><li>Esquecer de incluir a PK da forte na PK da fraca.</li><li>No 1:1, colocar a chave no lado errado, ignorando a participação total.</li><li>Não criar tabela para atributo multivalorado.</li></ul>' },
{ id:'c1410', m:14, q:'Mapeie GRAVADORA 1 — N CD, AUTOR N — N MUSICA e CLIENTE com fone*.',
  a:'<div class="pre">CD recebe cod_gravadora (FK)\nAUTOR_MUSICA(cod_autor, cod_musica)\nCLIENTE_FONE(cod_cli, fone)</div>' },
{ id:'c1411', m:14, q:'Como se mapeia uma AGREGAÇÃO?',
  a:'<p>Como <strong>entidades e relacionamentos normais</strong>. Como a agregação representa um relacionamento tratado como entidade, o mapeamento segue as mesmas regras já conhecidas.</p>' },

/* ── 15. Aspecto temporal ───────────────────────────────────────────── */
{ id:'c1501', m:15, q:'Qual é a REGRA DE OURO do aspecto temporal?',
  a:'<p><strong>ATUAL</strong> representa como está <em>agora</em>.</p><p><strong>TEMPORAL</strong> representa como está agora <em>e</em> como esteve no passado.</p>' },
{ id:'c1502', m:15, q:'O que acontece com um ATRIBUTO quando se quer guardar o histórico dele?',
  a:'<p>Ele vira uma <strong>nova entidade</strong>, com DATA.</p><p>Ex.: salário. Só o atual → <code>EMPREGADO(cod_emp, salario)</code>. Com histórico → <code>EMPREGADO (1) — (N) SALARIO(data, valor)</code>.</p>' },
{ id:'c1503', m:15, q:'O que acontece com um RELACIONAMENTO 1:1 ou 1:N quando se quer guardar o histórico?',
  a:'<p>Vira <strong>N:N com DATA</strong>.</p><p>Ex.: <code>EMPREGADO — LOCAÇÃO — MESA</code>. Só o atual: 1:1. Com histórico: N:N, porque um empregado passou por várias mesas e uma mesa foi de vários empregados.</p>' },
{ id:'c1504', m:15, q:'Por que a DATA vira identificadora do relacionamento?',
  a:'<p>Porque o mesmo par pode se relacionar <strong>mais de uma vez</strong>.</p><p>Se João foi alocado à Mesa 10 em 01/02/2023 e de novo em 10/05/2025, "João + Mesa 10" não distingue as duas. A DATA diferencia as ocorrências.</p>' },
{ id:'c1505', m:15, q:'O que fazer com dados antigos: arquivamento × estatísticas?',
  a:'<p><strong>Arquivamento:</strong> mover o detalhe para arquivos convencionais fora do BD — mas planejar o retorno, pois relacionamentos geram <strong>recuperação em cascata</strong>.</p><p><strong>Estatísticas:</strong> quando só interessam resultados (total, média, quantidade), guardar os <strong>compilados</strong> e descartar o detalhe.</p>' },
{ id:'c1506', m:15, q:'O que é recuperação em cascata no arquivamento?',
  a:'<p>Recuperar uma entidade arquivada exige recuperar também as entidades <strong>de que ela depende</strong>. Por isso o arquivamento precisa ser planejado, não improvisado.</p>' },
{ id:'c1507', m:15, q:'Qual erro clássico ao modelar histórico?',
  a:'<p>Guardar como <strong>colunas fixas</strong> — <code>salario1, salario2</code> — em vez de criar uma entidade.</p><p>E esquecer a DATA identificadora quando o mesmo relacionamento pode ocorrer mais de uma vez.</p>' },
{ id:'c1508', m:15, q:'Transforme o atributo "cargo" de um funcionário em modelo com histórico.',
  a:'<div class="pre">HISTORICO_CARGO(cod_emp PK/FK, data PK, cargo)</div><p>O atributo virou entidade e a data entrou na chave.</p>' },

/* ── 16. Normalização ───────────────────────────────────────────────── */
{ id:'c1601', m:16, q:'O que é NORMALIZAÇÃO e qual a ideia central?',
  a:'<p><strong>Organizar as tabelas</strong> para evitar informações repetidas, evitar inconsistências, separar assuntos diferentes e facilitar alterações.</p><p>Ideia central: <strong>não misturar assuntos diferentes na mesma tabela</strong>.</p>' },
{ id:'c1602', m:16, q:'Qual é "a frase que mais vale" sobre as formas normais?', hint:'Uma linha por FN',
  a:'<p><strong>1FN tira repetição. 2FN olha a chave composta. 3FN olha dependência entre atributos que não são chave.</strong></p>' },
{ id:'c1603', m:16, q:'O que a 1FN exige — e qual o cuidado?',
  a:'<p>A tabela <strong>não pode ter grupos de repetição</strong>, nem atributos multivalorados ou estruturas aninhadas. Separa-se o grupo que se repete numa nova tabela.</p><p><strong>Cuidado:</strong> 1FN não é "eliminar toda repetição". É eliminar <strong>grupos de repetição</strong>. A organização continua na 2FN e 3FN.</p>' },
{ id:'c1604', m:16, q:'Qual pergunta a 2FN faz — e em que tabelas ela se aplica?',
  a:'<p>Aplica-se a tabelas com <strong>chave composta</strong>. Pergunta: <strong>os atributos não-chave dependem da chave inteira?</strong></p><p>Se algum depende só de <strong>parte</strong> da chave, deve ser separado em outra tabela.</p>' },
{ id:'c1605', m:16, q:'Quais DUAS coisas a 3FN verifica?',
  a:'<ul><li>Existe atributo <strong>não-chave que depende de outro atributo não-chave</strong>? Se sim, separar.</li><li>Existe atributo <strong>calculado/derivado</strong> armazenado? Se sim, remover — evita inconsistência.</li></ul>' },
{ id:'c1606', m:16, q:'Dependência PARCIAL × dependência TRANSITIVA.',
  a:'<p><strong>Parcial</strong> (2FN) = o atributo depende de <strong>parte</strong> da chave composta.</p><p><strong>Transitiva</strong> (3FN) = o atributo não-chave depende de <strong>outro atributo não-chave</strong>.</p>' },
{ id:'c1607', m:16, q:'No Pedido de Compra, o que sai na 1FN?',
  a:'<p>O <strong>grupo de repetição</strong> — os itens.</p><div class="pre">PEDIDO(NR_PEDIDO, DATA, DEPTO_ORIGEM, DEPTO_DESTINO,\n       FUNC_SOL, FUNC_RESP, QTD_TOTAL)\nITENS_PEDIDO(NR_PEDIDO, ITEM, MATERIAL, QUANTIDADE)</div>' },
{ id:'c1608', m:16, q:'No Pedido de Compra, por que MATERIAL sai do ITENS_PEDIDO na 2FN?',
  a:'<p>Porque a chave é composta — <code>NR_PEDIDO + ITEM</code> — e <code>MATERIAL</code> <strong>não depende da chave inteira</strong>. Cria-se <code>COD_MATERIAL</code> e uma tabela própria.</p><div class="pre">ITENS_PEDIDO(NR_PEDIDO, ITEM, COD_MATERIAL, QUANTIDADE)\nMATERIAL(COD_MATERIAL, MATERIAL)</div><p><code>QUANTIDADE</code> depende dos dois e fica.</p>' },
{ id:'c1609', m:16, q:'No Pedido de Compra, o que acontece na 3FN?',
  a:'<p><code>DEPTO_*</code> e <code>FUNC_*</code> são <strong>assuntos próprios</strong> e viram tabelas. <code>QTD_TOTAL</code> é <strong>calculável</strong> (soma dos itens) e é <strong>removido</strong>.</p><div class="pre">PEDIDO(NR_PEDIDO, DATA, COD_DEPTO_ORIGEM, COD_DEPTO_DESTINO,\n       COD_FUNC_SOL, COD_FUNC_RESP)\nDEPARTAMENTO(COD_DEPTO, DESCRICAO)\nFUNCIONARIO(COD_FUNC, NOME)</div>' },
{ id:'c1610', m:16, q:'Por que QTD_TOTAL é removido? Que problema ele causaria?',
  a:'<p>É um <strong>dado derivado</strong> — a soma dos itens. Se armazenado, pode <strong>divergir</strong> da soma real e gerar inconsistência.</p>' },
{ id:'c1611', m:16, q:'REDUNDÂNCIA × DADO DERIVADO: qual a diferença?',
  a:'<p><strong>Redundância</strong> = repetir a mesma informação em vários lugares.</p><p><strong>Derivado</strong> = valor que pode ser <strong>calculado</strong> a partir de outros — e por isso não deve ser armazenado.</p>' },
{ id:'c1612', m:16, q:'Cite os 4 erros clássicos de normalização.',
  a:'<ul><li>Achar que a 1FN já elimina toda repetição.</li><li>Aplicar 2FN em tabela <strong>sem chave composta</strong>.</li><li>Manter um total calculado.</li><li><strong>Pular etapas</strong> — sempre 1FN → 2FN → 3FN, nessa ordem.</li></ul>' },
{ id:'c1613', m:16, q:'Normalize mentalmente uma NOTA FISCAL com itens até a 3FN. Que tabelas nascem?',
  a:'<div class="pre">NOTA(nr_nota, data, hora, cod_dest FK)\nDESTINATARIO(cod_dest, nome, cnpj, endereco)\nITENS_NOTA(nr_nota, item, cod_prod FK, quant, valor)\nPRODUTO(cod_prod, descricao, unid)\nTRANSPORTADOR(...)</div><p>E removem-se os totais calculados: total do item, base de cálculo, valor total.</p>' },
{ id:'c1614', m:16, q:'Normalize o CONTROLE DE ESTOQUE até a 3FN. Que tabelas nascem?',
  a:'<div class="pre">CONTROLE(nr_controle, data, cod_func_repositor FK, cod_func_resp FK)\nITENS_CONTROLE(nr_controle, item, cod_peca FK, qtde,\n               tipo_movimentacao, cod_setor FK)\nPECA(cod_peca, descricao)\nFUNCIONARIO(cod_func, nome)\nSETOR(cod_setor, descricao)</div>' },

/* ── 17. Estudos de caso / leitura de DER ───────────────────────────── */
{ id:'c1701', m:17, q:'Quais são os 7 passos do roteiro para resolver qualquer exercício de MER/DER?',
  a:'<ol><li>Ler o enunciado e marcar os <strong>substantivos</strong>.</li><li>Levantar os <strong>atributos</strong>.</li><li>Identificar os <strong>relacionamentos</strong> (verbos).</li><li>Definir a <strong>cardinalidade</strong>.</li><li>Verificar se algum atributo pertence ao <strong>relacionamento</strong>.</li><li>Procurar os <strong>casos especiais</strong>.</li><li>Transformar em <strong>Modelo Relacional</strong>.</li></ol>' },
{ id:'c1702', m:17, q:'Quais são os casos especiais que você deve procurar no passo 6?',
  a:'<p><strong>Auto-relacionamento · entidade fraca · atributo multivalorado · especialização · generalização · agregação · N:N</strong></p>' },
{ id:'c1703', m:17, q:'Engenharia reversa: tabela, coluna, FK e tabela intermediária viram o quê no DER?',
  a:'<ul><li>Tabela → <strong>entidade</strong></li><li>Coluna → <strong>atributo</strong></li><li>FK → <strong>possível relacionamento</strong></li><li>Tabela intermediária → geralmente um <strong>N:N</strong></li></ul>' },
{ id:'c1704', m:17, q:'Engenharia reversa: o que indica entidade fraca e o que indica auto-relacionamento?',
  a:'<p><strong>Entidade fraca:</strong> tabela que depende de outra — cuja PK começa com a PK de outra tabela.</p><p><strong>Auto-relacionamento:</strong> FK apontando para a <strong>própria tabela</strong>.</p>' },
{ id:'c1705', m:17, q:'Caso Casamento: por que PESSOA se liga a CASAMENTO por dois losangos?',
  a:'<p>Porque PESSOA participa em <strong>dois papéis</strong>: MARIDO e ESPOSA.</p><p>Graficamente há <strong>um só</strong> retângulo PESSOA, com dois losangos voltando a ele — é um auto-relacionamento via CASAMENTO.</p>' },
{ id:'c1706', m:17, q:'Caso Casamento: as duas resoluções do professor divergem nas cardinalidades. Qual adotar e por quê?',
  a:'<p>A leitura <strong>N:1</strong> é a mais defensável: um mesmo local é nascimento de <strong>várias</strong> pessoas, e uma profissão é exercida por várias pessoas.</p><p>Mas as duas estão certas <em>dentro das hipóteses adotadas</em> — o enunciado manda adicionar hipóteses. <strong>Escreva a hipótese embaixo do desenho.</strong></p>' },
{ id:'c1707', m:17, q:'Caso Empregado/Projeto: quais são as 4 sacadas do exercício?',
  a:'<ol><li><strong>Entidade fraca:</strong> DEPENDENTE (retângulo duplo) depende de EMPREGADO.</li><li><strong>Auto-relacionamento:</strong> SuperIdent → EMPREGADO supervisiona EMPREGADO.</li><li><strong>N:N:</strong> TrabalhaNo liga Empregado e Projeto e guarda HORAS.</li><li>A tabela TrabalhaNo <strong>existe porque há N:N</strong>.</li></ol>' },
{ id:'c1708', m:17, q:'Caso Empregado/Projeto: qual a cardinalidade de Empregado–Departamento nos dois relacionamentos?',
  a:'<p><strong>Trabalha:</strong> N:1 — vários empregados por departamento.</p><p><strong>Gerencia:</strong> 1:1 — um gerente por departamento (vem do <code>IdentGer</code>).</p>' },
{ id:'c1709', m:17, q:'Caso Empregado/Projeto: duas turmas usaram nomes diferentes nos losangos. O que a correção realmente procura?',
  a:'<p>O nome do losango é <strong>escolha de quem modela</strong>. O que não pode mudar são as <strong>cardinalidades</strong>, a <strong>entidade fraca</strong>, o <strong>auto-relacionamento</strong> e o <strong>N:N com atributo</strong>.</p>' },
{ id:'c1710', m:17, q:'Caso Engenho ABC: quais três estruturas especiais aparecem no diagrama?',
  a:'<ul><li><strong>Especialização</strong> — triângulo entre FUNCIONARIO e ENGENHEIRO.</li><li><strong>Multivalorado</strong> — FONE em elipse dupla no CLIENTE.</li><li><strong>Atributos do relacionamento</strong> — DATA e NR_DIAS pendurados no losango CONTRATO.</li></ul>' },
{ id:'c1711', m:17, q:'Caso Engenho ABC: escreva o Modelo Relacional final.',
  a:'<div class="pre">DEPARTAMENTO(COD_DEPTO PK, DESCRICAO, LOCALIZACAO)\nFUNCIONARIO(CPF PK, NOME, ENDERECO, CARGO, SALARIO)\nENGENHEIRO(CPF PK/FK, CREA, ESPECIALIDADE)\nCLIENTE(COD_CLI PK, NOME, ENDERECO)\nCLIENTE_FONE(COD_CLI PK/FK, FONE PK)\nPROJETO(COD_PROJ PK, TITULO, DESCRICAO, LOC_GEO,\n        PRAZO_ENTREGA, CUSTO, COMPLEXIDADE, COD_CLI FK)\nCONTRATO(COD_DEPTO FK, CPF FK, DATA, NR_DIAS)\nGERENCIAR(COD_PROJ FK, CPF FK, DATA)</div>' },
{ id:'c1712', m:17, q:'Caso Pedidos: qual o macete de leitura e o que amarra o caso à normalização?',
  a:'<p><strong>Macete:</strong> se a chave de uma tabela aparece em outra, ela virou FK e criou um relacionamento.</p><p><strong>Amarra com a 3FN:</strong> <code>SUB_TOTAL</code> (= QTD × VL_PROD) e <code>TOTAL_PED</code> são <strong>valores calculados</strong> — sairiam na normalização.</p>' },
{ id:'c1713', m:17, q:'Caso Atendimento técnico: quantos N:N há e quais são?',
  a:'<p><strong>Dois</strong>, ambos saindo de ATENDIMENTO:</p><ul><li><code>SERV_PRESTADO</code> — ATENDIMENTO N—N SERVICO</li><li><code>SOL_PRESTADA</code> — ATENDIMENTO N—N SOLUCAO</li></ul><p>Há ainda <code>ACAO_SERV</code> — SITUACAO_SERV N—N FUNCIONARIO_CLI.</p>' },
{ id:'c1714', m:17, q:'Qual é o melhor exercício-síntese da disciplina?',
  a:'<p>Refazer do zero o MER do <strong>Atendimento técnico</strong>, a partir do formulário de manutenção, e depois comparar com a resolução do professor.</p><p>É o diagrama mais completo: várias entidades, 1:N e N:N, multivalorado e atributos-chave sublinhados.</p>' }

];
