/* =========================================================================
   CONTEXTO E EXPLICAÇÃO SIMPLES DAS QUESTÕES

   c  cenário — mostrado ANTES das alternativas, para você ter em que se
      apoiar antes de escolher
   s  em uma frase — a explicação simples, mostrada assim que você responde,
      antes do detalhe técnico
   ========================================================================= */

const QUIZ_EXTRA = {

/* ── 1 ──────────────────────────────────────────────────────────────── */
q101: { c: 'Um gerente olha uma planilha de vendas soltas e pede "me diga se batemos a meta". Alguém precisa saber qual conta fazer.',
        s: 'Conhecimento é o "como fazer"; ele fica embaixo do processo, não no fim da linha.' },
q102: { c: 'Duas telas do mesmo sistema: uma lista 4.000 vendas individuais; a outra mostra uma linha só com o total do mês.',
        s: 'Dado organizado a ponto de apoiar uma decisão já é informação.' },
q103: { c: 'O relatório mensal tem 80 páginas, todos os números conferidos, e a reunião termina sem nenhuma decisão.',
        s: 'Informação demais atrapalha tanto quanto informação de menos.' },
q104: { c: 'O cadastro tem o CPF de um cliente digitado errado. O sistema processa tudo normalmente e emite a nota.',
        s: 'Se o dado entra errado, nenhum processamento conserta na saída.' },
q105: { c: 'Dois relatórios custam o mesmo para produzir. Um muda a decisão da diretoria; o outro é arquivado sem ser lido.',
        s: 'Informação vale pelo que ela permite decidir, não pelo trabalho que deu.' },
q106: { c: 'Questão de eliminação: três das quatro alternativas estão na lista das nove características.',
        s: 'Redundância é problema a evitar, não qualidade a buscar.' },

/* ── 2 ──────────────────────────────────────────────────────────────── */
q201: { c: 'Um aluno lista "entrada, processamento e saída" na prova e perde ponto.',
        s: 'Sem feedback, o sistema erra e continua errando do mesmo jeito.' },
q202: { c: 'O RH digita as horas, o sistema faz as contas e a impressora cospe o contracheque.',
        s: 'Processamento é o que acontece no meio: a transformação.' },
q203: { c: 'Você desenha o SI de uma loja e precisa dizer onde o PostgreSQL se encaixa no desenho.',
        s: 'O banco é onde os dados ficam e de onde eles voltam.' },
q204: { c: 'Assar um bolo é um sistema. Um sistema de folha de pagamento também. Não são a mesma categoria.',
        s: 'SI é um tipo especial de sistema — o que lida com dados e tem feedback.' },

/* ── 3 ──────────────────────────────────────────────────────────────── */
q301: { c: 'Você baixa o instalador do MySQL. Ainda não existe nenhuma tabela, nenhum dado.',
        s: 'O software é o SGBD; o banco é o que ele guarda depois.' },
q302: { c: 'De um lado o DBeaver na sua máquina; do outro, o processo que guarda os dados e controla quem entra.',
        s: 'Back end é quem guarda e protege; front end é quem pede.' },
q303: { c: 'Você apaga a aplicação e reinstala do zero. As FKs e as regras entre as tabelas continuam valendo.',
        s: 'O banco guarda os relacionamentos dentro dele, não no código da aplicação.' },
q304: { c: 'A empresa migrou de sistema e tem arquivos .csv com 200 mil clientes para colocar no banco novo.',
        s: 'Carga é para encher o banco pela primeira vez.' },
q305: { c: 'O código do cliente aparece em CLIENTE, PEDIDO e ITENS_PEDIDO. Isso é errado?',
        s: 'A meta é controlar a repetição, não bani-la — as FKs repetem valores de propósito.' },
q306: { c: 'Alguém pergunta se uma view ou uma stored procedure "fica dentro do banco".',
        s: 'Fica: views, índices, procedimentos e funções também são objetos do banco.' },

/* ── 4 ──────────────────────────────────────────────────────────────── */
q401: { c: 'Nos dois modelos os registros se ligam uns aos outros. A diferença é uma só.',
        s: 'Hierárquico: um pai. Rede: vários pais.' },
q402: { c: 'Uma pegadinha frequente: alguém diz que os outros modelos "não têm relacionamento".',
        s: 'Relação, aqui, é o nome matemático de tabela.' },
q403: { c: 'Quatro situações do dia a dia. Só uma delas tem estrutura de árvore de verdade.',
        s: 'Pasta tem um pai só; as outras três situações têm vários.' },
q404: { c: 'Dois dos cinco modelos trazem ideias da programação orientada a objetos.',
        s: 'Objeto-relacional soma métodos às tabelas; objeto junta dados e processos.' },

/* ── 5 ──────────────────────────────────────────────────────────────── */
q501: { c: 'A empresa tem 1000 PCs com o sistema instalado. Sai uma versão nova toda semana.',
        s: 'Com a regra de negócio no cliente, cada nova versão precisa ir de máquina em máquina.' },
q502: { c: 'A empresa quer parar de mandar técnico de mesa em mesa a cada atualização.',
        s: 'A regra de negócio sobe para o servidor de aplicação.' },
q503: { c: 'Você acessa o sistema da faculdade pelo Chrome, sem ter instalado nada.',
        s: 'Na de 4 camadas, nem a tela fica na sua máquina — vem do servidor web.' },
q504: { c: 'A empresa roda apresentação, regra e banco no mesmo servidor. Isso deixa de ser 3 camadas?',
        s: 'Camada é divisão lógica; onde cada uma roda é outra decisão.' },
q505: { c: 'Depois de centralizar tudo num servidor, ele passou a atender 1000 pessoas ao mesmo tempo.',
        s: 'Centralizar concentra a carga — o servidor vira o gargalo.' },
q506: { c: 'Vários computadores em rede dividem entre si o processamento de uma mesma tarefa pesada.',
        s: 'Uma tarefa só, espalhada por várias máquinas.' },

/* ── 6 ──────────────────────────────────────────────────────────────── */
q601: { c: 'O professor entrega um texto de meia página e pede "o banco de dados desse problema".',
        s: 'Primeiro a ideia, depois o desenho, depois as tabelas, e só no fim o SGBD.' },
q602: { c: 'Na mesma questão aparecem "faça o MER" e "faça o DER". Não é repetição.',
        s: 'MER é a decisão; DER é o desenho da decisão.' },
q603: { c: 'Você está lendo um DER e vê uma elipse desenhada com dois contornos.',
        s: 'Contorno duplo na elipse significa vários valores.' },
q604: { c: 'O nome do cliente está gravado em quatro tabelas, e numa delas está desatualizado.',
        s: 'Repetir dado gasta espaço e cria versões que se contradizem.' },
q605: { c: 'O mesmo modelo conceitual vai ser implementado em Oracle numa empresa e em MySQL na outra.',
        s: 'O MER fala do negócio, e negócio não muda de acordo com o SGBD.' },
q606: { c: 'Você desenhou seis losangos. Quantas tabelas eles vão gerar?',
        s: 'Losango vira FK quando é 1:N ou 1:1, e vira tabela quando é N:N.' },

/* ── 7 ──────────────────────────────────────────────────────────────── */
q701: { c: 'Você recebe o enunciado e tem que decidir por onde começar a leitura.',
        s: 'Substantivo aponta entidade; verbo aponta relacionamento.' },
q702: { c: 'Você criou uma entidade CATEGORIA que tem só a coluna "nome".',
        s: 'Com um atributo só, ela não se sustenta — vira atributo de outra entidade.' },
q703: { c: 'O endereço do cliente aparece no formulário dividido em cinco campinhos.',
        s: 'Um valor só, quebrado em partes.' },
q704: { c: 'Você lê a notação textual de um exercício e vê um asterisco depois de um nome de coluna.',
        s: 'O asterisco marca "vários valores".' },
q705: { c: 'O cliente liga pedindo para cadastrar o quarto telefone. Só existem três colunas.',
        s: 'Vários valores do mesmo tipo pedem tabela, não colunas numeradas.' },
q706: { c: 'A entidade CD no seu modelo, e o disco "Mais do Mesmo" na estante da sua casa.',
        s: 'Uma é a categoria; a outra é um exemplar dela.' },
q707: { c: 'Alguém criou uma entidade COR ligada a PRODUTO, com um único campo.',
        s: 'Se só descreve, é atributo; se tem vida própria, é entidade.' },

/* ── 8 ──────────────────────────────────────────────────────────────── */
q801: { c: 'Você precisa de uma coluna que localize uma linha entre um milhão, sempre a mesma.',
        s: 'A chave não pode repetir, não pode ser ambígua e não pode mudar.' },
q802: { c: 'O pedido 100 tem cinco itens. Com PRIMARY KEY (nr_pedido), o banco recusa o segundo item.',
        s: 'O número do pedido se repete nos itens — só a dupla identifica a linha.' },
q803: { c: 'Você quer listar os pedidos por data, do mais recente ao mais antigo.',
        s: 'Serve para achar e ordenar, não para identificar.' },
q804: { c: 'Em CLIENTE_FONE(cod_cli, fone), a coluna cod_cli faz duas coisas ao mesmo tempo.',
        s: 'Ela identifica junto com o fone, e ao mesmo tempo aponta para CLIENTE.' },
q805: { c: 'Você usou o nome como chave. Entra o segundo "João Silva" e o primeiro muda de nome ao casar.',
        s: 'Nome repete e muda — as duas coisas que uma chave não pode fazer.' },
q806: { c: 'Você olha uma coluna qualquer e precisa decidir se ela é PK ou FK.',
        s: 'PK diz quem a linha é; FK diz para quem a linha aponta.' },

/* ── 9 ──────────────────────────────────────────────────────────────── */
q901: { c: 'Um departamento tem 40 funcionários. Cada funcionário está em um departamento.',
        s: 'A chave desce para o lado que tem muitos.' },
q902: { c: 'Tente escrever uma tabela ALUNO com uma coluna que guarde as cinco disciplinas dele.',
        s: 'Uma célula guarda um valor — muitos para muitos não cabe ali.' },
q903: { c: 'Você desenhou DEPARTAMENTO 1 — 1 GERENTE e ficou com a sensação de que algo está sobrando.',
        s: '1:1 quase sempre é um convite a repensar o modelo.' },
q904: { c: 'A definição completa de um relacionamento tem três partes, e a cardinalidade é só uma delas.',
        s: 'Nome, opcionalidade e cardinalidade.' },
q905: { c: 'Machado de Assis escreveu vários livros. "Os Sertões" tem mais de um autor em algumas edições comentadas.',
        s: 'Muitos dos dois lados sempre pede uma tabela no meio.' },
q906: { c: 'Você vai escrever o CREATE TABLE de CLIENTE 1 — N PEDIDO. Três das opções estão erradas.',
        s: 'Basta uma coluna em PEDIDO apontando para CLIENTE.' },

/* ── 10 ─────────────────────────────────────────────────────────────── */
q1001: { c: 'Duas perguntas parecidas na mesma questão: "quantos de cada lado" e "quantas entidades".',
         s: 'Grau conta caixas; cardinalidade conta quantos de cada lado.' },
q1002: { c: 'No desenho, o retângulo FUNCIONARIO aparece nas duas pontas do mesmo losango.',
         s: 'Aparecer duas vezes no desenho não faz dela duas entidades.' },
q1003: { c: 'Você recebe seis tabelas e precisa achar o auto-relacionamento sem ler o enunciado.',
         s: 'A coluna que aponta de volta para a própria tabela entrega o auto-relacionamento.' },
q1004: { c: 'Tentação comum: desenhar um retângulo SUPERVISOR ao lado do retângulo FUNCIONARIO.',
         s: 'O chefe está cadastrado na mesma tabela que os outros — é a mesma entidade.' },
q1005: { c: 'Um motor é feito de várias peças, e cada peça pode entrar em vários motores.',
         s: 'Grau e cardinalidade são perguntas independentes — um auto-relacionamento tem as duas.' },
q1006: { c: 'Materiais, requisições e pedidos num losango só — e o desenho não convence ninguém.',
         s: 'Quando o ternário fica forçado, empacote um dos relacionamentos.' },

/* ── 11 ─────────────────────────────────────────────────────────────── */
q1101: { c: 'Você está lendo um DER e vê um retângulo desenhado com dois contornos.',
         s: 'Contorno duplo no retângulo significa que ela depende de outra para existir.' },
q1102: { c: 'Dois funcionários diferentes têm um dependente chamado Pedro, cadastrados no mesmo dia.',
         s: 'Sem a chave do funcionário junto, os dois Pedros viram o mesmo registro.' },
q1103: { c: 'É o relacionamento sem o qual a entidade fraca não conseguiria ser identificada.',
         s: 'É ele que empresta a chave que falta.' },
q1104: { c: 'O empregado 10 fez 20 horas no projeto A e 15 horas no projeto B.',
         s: 'As horas só existem quando você diz de qual empregado em qual projeto.' },
q1105: { c: 'As duas aparecem no desenho como retângulo duplo com chave composta.',
         s: 'O que muda é o motivo: uma nasce da dependência, a outra do N:N.' },
q1106: { c: 'Você abre o esquema e vê uma tabela com duas FKs e quase nada mais.',
         s: 'Tabela no meio de duas outras é quase sempre um N:N desmontado.' },

/* ── 12 ─────────────────────────────────────────────────────────────── */
q1201: { c: 'Uma secretária é uma funcionária. Um funcionário tem um departamento. Duas relações diferentes.',
         s: '"É-um" herda tudo do pai; "tem-um" só aponta para outra entidade.' },
q1202: { c: 'Um funcionário pode ser engenheiro e gerente ao mesmo tempo? O símbolo no triângulo responde.',
         s: 'O "+" quer dizer: escolha uma, e só uma.' },
q1203: { c: 'A mesma linha do desenho lida de baixo para cima e de cima para baixo.',
         s: 'É a mesma relação, mudando o sentido da leitura.' },
q1204: { c: 'O hospital não quer acompanhar o médico nem o paciente, e sim o atendimento entre os dois.',
         s: 'Você embrulha um relacionamento e trata o pacote como se fosse entidade.' },
q1205: { c: 'Na tabela ENGENHEIRO, a coluna cpf tem duas funções ao mesmo tempo.',
         s: 'Ela identifica o engenheiro e aponta para o funcionário — é a mesma pessoa.' },
q1206: { c: 'As duas transformam relacionamento em algo que se relaciona. Então qual usar quando?',
         s: 'Associativa junta duas entidades; agregação liga um relacionamento a uma terceira.' },

/* ── 13 ─────────────────────────────────────────────────────────────── */
q1301: { c: 'Existe um pedido apontando para o cliente 99. O cliente 99 nunca foi cadastrado.',
         s: 'Referência apontando para o vazio é o que a integridade referencial impede.' },
q1302: { c: 'Você digita DELETE FROM cliente WHERE cod_cli = 1, e esse cliente tem 40 pedidos.',
         s: 'Ou o banco te impede, ou ele leva os filhos junto.' },
q1303: { c: 'São duas regras complementares, cada uma cuidando de uma chave.',
         s: 'Uma cuida de quem a linha é; a outra, de para quem ela aponta.' },
q1304: { c: 'Você criou as tabelas sem escrever nenhuma cláusula FOREIGN KEY.',
         s: 'O banco só protege o que você mandou ele proteger.' },

/* ── 14 ─────────────────────────────────────────────────────────────── */
q1401: { c: 'Você tem CLIENTE 1 — N PEDIDO no DER e está prestes a criar uma terceira tabela.',
         s: 'Uma coluna a mais resolve — tabela nova seria desperdício.' },
q1402: { c: 'ALUNO e DISCIPLINA, com a nota de cada aluno em cada disciplina.',
         s: 'As duas chaves juntas viram a chave da tabela nova.' },
q1403: { c: 'Todo país tem uma capital, mas nem toda cidade é capital.',
         s: 'A chave vai para o lado que participa sempre.' },
q1404: { c: 'Nos dois casos a chave de uma tabela vai parar dentro de outra. O destino é que muda.',
         s: 'No 1:N ela fica de fora da chave; na fraca ela entra na chave.' },
q1405: { c: 'Uma conta é corrente ou poupança, nunca as duas — e sempre é uma das duas.',
         s: 'Só dá para apagar a tabela do meio quando toda ocorrência cai em exatamente uma subclasse.' },
q1406: { c: 'O cliente tem três telefones hoje e pode ter cinco amanhã.',
         s: 'Vários valores viram linhas, não colunas.' },
q1407: { c: 'O exemplar 2 do livro 500 e o exemplar 2 do livro 700 são coisas diferentes.',
         s: 'A chave da forte entra na chave da fraca — sem ela, o registro fica ambíguo.' },
q1408: { c: 'Três das quatro alternativas descrevem procedimentos corretos de mapeamento.',
         s: 'Relacionamento 1:N se resolve com coluna, não com tabela.' },

/* ── 15 ─────────────────────────────────────────────────────────────── */
q1501: { c: 'O RH pergunta: você quer o salário de hoje, ou todos os salários que a pessoa já teve?',
         s: 'Ou você guarda uma foto, ou você guarda o filme inteiro.' },
q1502: { c: 'O salário mudou seis vezes em quatro anos e o RH quer os seis valores com as datas.',
         s: 'Se um atributo precisa de várias versões datadas, ele deixa de caber numa coluna.' },
q1503: { c: 'Cada empregado tem uma mesa hoje. O RH quer saber todas as mesas por onde ele passou.',
         s: 'Com histórico, os dois lados passam a ter muitos.' },
q1504: { c: 'João sentou na Mesa 10 em 2023, saiu, e voltou para a Mesa 10 em 2025.',
         s: 'Sem a data, os dois registros ficam idênticos — e chave não aceita duplicata.' },
q1505: { c: 'O banco cresceu 400 GB guardando dez anos de histórico. Alguma coisa precisa sair.',
         s: 'Arquivar guarda o detalhe em outro lugar; estatística joga o detalhe fora e fica com o resumo.' },
q1506: { c: 'Alguém criou as colunas salario1, salario2 e salario3 para guardar as últimas mudanças.',
         s: 'É o mesmo erro do telefone em três colunas, agora aplicado ao tempo.' },

/* ── 16 ─────────────────────────────────────────────────────────────── */
q1601: { c: 'A tabela tem uma linha por item, com data, departamento e solicitante repetidos em todas.',
         s: 'A 1FN só desmonta o bloco que se repete dentro da linha — o resto fica para depois.' },
q1602: { c: 'Uma tabela tem PK só de NR_PEDIDO. Faz sentido perguntar se algo depende de "parte" dela?',
         s: 'Sem chave composta não existe "metade da chave" para depender.' },
q1603: { c: 'Sobrou o nome do departamento na tabela de pedidos, e um campo QTD_TOTAL somado à mão.',
         s: 'Não-chave puxando não-chave, e campo que dá para calcular.' },
q1604: { c: 'A chave é NR_PEDIDO + ITEM. "Lápis" depende do pedido, do número do item, ou de nenhum dos dois?',
         s: 'O nome do material não muda conforme o pedido — ele depende só do material.' },
q1605: { c: 'Alguém edita a quantidade de um item direto no banco e esquece de refazer o total.',
         s: 'Total guardado é total que vai desencontrar da soma mais cedo ou mais tarde.' },
q1606: { c: 'Os dois nomes aparecem juntos na prova e são fáceis de trocar de lugar.',
         s: 'Parcial é depender de meia chave; transitiva é depender de quem não é chave.' },
q1607: { c: 'Três das quatro alternativas descrevem exatamente o que se deve fazer ao normalizar.',
         s: 'A 2FN só tem o que fazer quando a chave tem mais de uma coluna.' },
q1608: { c: 'Depois da 3FN, cada tabela do Pedido de Compra fala de um assunto só.',
         s: 'Cada assunto na sua tabela — é isso que a normalização faz.' },

/* ── 17 ─────────────────────────────────────────────────────────────── */
q1701: { c: 'No esquema original: Dependente(Nome, Sexo, DataNasc, Parentesco, IdentEmp). Nenhum código próprio.',
         s: 'Contorno duplo = ela precisa da chave de outra para se identificar.' },
q1702: { c: 'No esquema: Empregado(Ident, ..., DepNum, SuperIdent). SuperIdent também é um Ident de empregado.',
         s: 'O losango sai e volta para a mesma caixa.' },
q1703: { c: 'No enunciado: "entre os funcionários há engenheiros, com CREA e especialidade".',
         s: 'Triângulo é o símbolo de "é um tipo de".' },
q1704: { c: 'No enunciado: "clientes (código, nome, endereço, fones)". Fones, no plural.',
         s: 'Elipse dupla sempre vira tabela nova no relacional.' },
q1705: { c: 'No esquema: Casamento(casamID, MaridoPessoaID, EsposaPessoaID, DataCasamento). Duas colunas apontam para Pessoa.',
         s: 'A mesma entidade entra duas vezes, cumprindo funções diferentes.' },
q1706: { c: 'O enunciado dizia "adicionando as hipóteses que julgar necessárias". Duas turmas leram de formas diferentes.',
         s: 'Quando o enunciado pede hipótese, declarar a sua faz parte da resposta.' },
q1707: { c: 'Duas situações parecidas: uma tabela cuja PK começa com a PK de outra, e uma com duas FKs formando a PK.',
         s: 'Uma FK herdada na chave é fraca; duas FKs de tabelas diferentes na chave é N:N.' },
q1708: { c: 'Na planilha: SUB_TOTAL ao lado de QTD e VL_PROD, e TOTAL_PED no fim de cada linha.',
         s: 'O que dá para calcular não precisa ser guardado.' },
q1709: { c: 'Uma turma escreveu POSSUIR, a outra escreveu TEM. Nenhuma das duas perdeu ponto.',
         s: 'A correção olha a estrutura, não o vocabulário.' },
q1710: { c: 'Folha em branco, enunciado na mão, e você precisa de um primeiro movimento que não trave.',
         s: 'Comece grifando substantivos — eles são a matéria-prima do desenho.' }

};
