/* =========================================================================
   CONTEXTO E RESPOSTA CURTA DOS FLASHCARDS

   c  contexto — a situação concreta, mostrada ANTES da pergunta, para você
      ter em que se apoiar na hora de responder
   s  em uma frase — a resposta curta, mostrada ANTES da explicação longa
   ========================================================================= */

const CARDS_EXTRA = {

/* ── 1. Dado, Informação e Conhecimento ─────────────────────────────── */
c101: { c: 'Uma loja registra cada venda do dia. No fim do mês alguém precisa decidir a meta do próximo mês.',
        s: 'Dado entra, processo transforma, informação sai — e o conhecimento é o que sabe fazer a transformação.' },
c102: { c: 'Você abre uma planilha e vê uma célula com o número 8. Sem cabeçalho, sem nada em volta.',
        s: 'Dado é o fato cru, sem contexto nenhum.' },
c103: { c: 'A mesma planilha, agora com cabeçalho: "vendas de terça — 8 unidades, 30% acima da média".',
        s: 'Informação é o dado organizado a ponto de ajudar alguém a decidir.' },
c104: { c: 'Duas pessoas olham os mesmos números. Uma sabe qual média calcular e por quê; a outra não.',
        s: 'Conhecimento são as regras que você aplica sobre os dados.' },
c105: { s: 'Dado é a madeira, conhecimento é saber usar a serra, informação é a cadeira pronta.' },
c106: { c: 'Um relatório lindo, colorido, com 40 gráficos. O gerente lê e continua sem saber o que fazer.',
        s: 'O valor está em quanto ela ajuda a decidir — não em volume nem em beleza.' },
c107: { c: 'Questão objetiva clássica: "assinale a alternativa que NÃO é característica da boa informação".',
        s: 'Precisa, completa, econômica, flexível, confiável, relevante, simples, em tempo e verificável.' },
c108: { c: 'O relatório de estoque de segunda-feira chega na sexta. Os números estão todos certos.',
        s: 'Em tempo — informação certa que chega tarde já não serve para decidir.' },
c109: { s: 'Entra Lixo, Sai Lixo: dado errado na entrada vira informação errada na saída.' },
c110: { c: 'O sistema passa a mandar 200 alertas por dia em vez de 5. Ninguém mais abre nenhum.',
        s: 'Excesso vira sobrecarga, e sobrecarga trava a decisão — é a característica Simples.' },
c111: { s: 'Informação é o resultado; conhecimento são as regras que produziram esse resultado.' },

/* ── 2. Sistemas e SI ───────────────────────────────────────────────── */
c201: { c: 'Assar um bolo e administrar um hospital: os dois são sistemas, em escalas muito diferentes.',
        s: 'Conjunto de elementos que interagem para atingir um objetivo.' },
c202: { c: 'Um sistema de folha de pagamento: recebe horas, calcula, emite contracheque e aceita correções.',
        s: 'É o sistema especializado em dados — com entrada, processamento, saída e feedback.' },
c203: { c: 'A pergunta que mais aparece em prova pede os componentes, e a maioria esquece justamente o quarto.',
        s: 'Entrada, processamento, saída e — o esquecido — feedback.' },
c204: { c: 'O funcionário confere o contracheque e vê que faltaram duas horas extras. Ele reclama no RH.',
        s: 'Feedback é a saída voltando para corrigir a entrada ou o processamento.' },
c205: { c: 'Você está montando um sistema de vendas e alguém pergunta: "onde o banco entra nisso?".',
        s: 'Ele é a camada de dados: guarda e devolve o que o sistema manipula.' },
c206: { c: 'Uma universidade: entram estudantes e professores, sai gente formada e pesquisa.',
        s: 'Entrada → processamento → saída, sempre orientado por uma meta.' },

/* ── 3. BD e SGBD ───────────────────────────────────────────────────── */
c301: { s: 'Conjunto coerente e lógico de dados relacionados, com significado próprio, representando o mundo real.' },
c302: { c: 'Você instala o MySQL na máquina. O que você instalou, tecnicamente, não é um banco de dados.',
        s: 'É a coleção de programas que cria estruturas, mantém dados e gerencia transações — DBMS em inglês.' },
c303: { c: 'Numa prova objetiva: "O Oracle é um exemplo de ___". Muita gente marca "banco de dados".',
        s: 'O banco é o conteúdo; o SGBD é o programa que cuida do conteúdo.' },
c304: { c: 'Você abre o DBeaver no seu computador e ele se conecta a um servidor PostgreSQL na nuvem.',
        s: 'Servidor (back end) é o SGBD; clientes (front ends) são as aplicações que rodam sobre ele.' },
c305: { c: 'Pergunta de listar: "cite as principais características de um SGBD".',
        s: 'Redundância, compartilhamento, acesso, esquematização, backup e segurança.' },
c306: { c: 'Você apaga a aplicação inteira e reinstala do zero. Os relacionamentos entre as tabelas continuam lá.',
        s: 'Os relacionamentos ficam guardados no próprio banco, não só no código da aplicação.' },
c307: { c: 'É segunda de manhã e o DBA precisa restaurar o banco depois de uma falha no fim de semana.',
        s: 'Carga, descarregamento/recarregamento, reorganização e rotinas estatísticas.' },
c308: { s: 'É quem administra o banco: backup, carga, reorganização, desempenho, segurança e disponibilidade.' },
c309: { c: 'Alguém pergunta o que exatamente está guardado dentro de um banco relacional além das linhas.',
        s: 'Guardar os objetos do dicionário de dados — tabelas, views, índices, procedimentos e funções.' },
c310: { c: 'Dois atendentes vendem a última poltrona do cinema no mesmo segundo.',
        s: 'Acesso simultâneo pode gerar inconsistência — daí a necessidade de controle de concorrência.' },
c311: { c: 'Você repete o código do cliente em cinco tabelas. Isso é redundância — e é aceitável.',
        s: 'Errado: a característica é controle de redundância, não eliminação total.' },

/* ── 4. Tipos de BD ─────────────────────────────────────────────────── */
c401: { c: 'A aula lista cinco modelos em ordem histórica, do mais antigo ao mais recente.',
        s: 'Hierárquico, rede, relacional, objeto-relacional e objeto.' },
c402: { c: 'Pense na pasta Documentos do seu Windows: ela está dentro de uma pasta só.',
        s: 'Como uma árvore, em que cada filho tem exatamente um pai.' },
c403: { c: 'Um funcionário está em três projetos ao mesmo tempo. Ele tem três "pais".',
        s: 'Como registros ligados a vários outros — generaliza o hierárquico porque permite mais de um pai.' },
c404: { c: 'É a pergunta de uma linha que separa os dois modelos numa prova objetiva.',
        s: 'Quantos pais um registro pode ter: hierárquico um, rede vários.' },
c405: { c: 'Uma planilha do Excel é a intuição mais próxima: linhas, colunas e um código ligando abas.',
        s: 'Linhas e colunas em tabelas, com os relacionamentos feitos por chaves.' },
c406: { c: 'A pegadinha: alguém afirma que só o modelo relacional tem relacionamentos entre dados.',
        s: 'De "relação", o termo matemático para tabela — não de "ter relacionamentos".' },
c407: { s: 'Objeto-relacional soma métodos às tabelas; objeto guarda dados e processos juntos.' },

/* ── 5. Arquiteturas ────────────────────────────────────────────────── */
c501: { c: 'A aula apresenta como evolução histórica: cada arquitetura resolve o problema da anterior.',
        s: 'Centralizado, cliente/servidor, 3 camadas, 4 camadas e distribuído.' },
c502: { c: 'Anos 70: uma sala refrigerada com um mainframe e dezenas de terminais sem processamento nenhum.',
        s: 'Uma máquina faz tudo — e o problema é o custo altíssimo do hardware.' },
c503: { c: 'Um sistema .exe instalado em 1000 PCs de uma rede, todos apontando para o servidor de banco.',
        s: 'Descentralizar o processamento — mas aí é preciso atualizar o programa em cada estação.' },
c504: { c: 'A empresa cansou de mandar técnico de mesa em mesa a cada nova versão do sistema.',
        s: 'Tira a regra de negócio e põe num servidor de aplicação — atualiza-se em um ponto só.' },
c505: { c: 'Hoje você acessa o sistema da faculdade pelo navegador, sem instalar nada.',
        s: 'Tira também a apresentação, que vai para um servidor web — o acesso passa a ser por browser.' },
c506: { c: 'Questão objetiva: as duas arquiteturas têm servidor de aplicação e banco. O que muda?',
        s: 'A de 4 camadas também tira a apresentação do cliente, que vira um browser.' },
c507: { s: 'Uma única tarefa se espalha por várias máquinas em rede.' },
c508: { c: 'Você centralizou tudo num servidor e agora ele é o gargalo de 1000 usuários.',
        s: 'Desempenho e dimensionamento dos servidores tornam-se críticos.' },
c509: { c: 'A empresa roda apresentação, regra e banco no mesmo servidor físico. Ainda são 3 camadas?',
        s: 'Errado: são camadas lógicas, e podem estar na mesma máquina.' },

/* ── 6. Visão geral da modelagem ────────────────────────────────────── */
c601: { c: 'O professor entrega um texto de meia página e pede "o banco". Existe um caminho fixo até lá.',
        s: 'Enunciado → MER → DER → Modelo Relacional → Modelo Físico.' },
c602: { c: 'Numa prova, "faça o MER" e "faça o DER" costumam vir na mesma questão.',
        s: 'MER é o modelo, o conjunto de decisões; DER é o desenho desse modelo.' },
c603: { c: 'O mesmo MER pode virar MySQL, Oracle ou PostgreSQL sem mudar uma linha do desenho.',
        s: 'Porque descreve o negócio, não um produto — não depende de SGBD nenhum.' },
c604: { c: 'Três perguntas diferentes sobre a mesma coisa: o quê, como em tabelas, como neste SGBD.',
        s: 'Conceitual é o quê, lógico é como em tabelas, físico é como neste SGBD.' },
c605: { c: 'O nome do cliente está gravado em quatro tabelas diferentes. Uma delas está desatualizada.',
        s: 'Redundância e desperdício de espaço.' },
c606: { s: 'Retângulo é entidade, retângulo duplo é entidade fraca, losango é relacionamento.' },
c607: { s: 'Elipse é atributo, sublinhada é chave, dupla é multivalorado, triângulo é especialização.' },
c608: { s: 'Sintaxe robusta, comunicação fácil, fácil de manter, integra aplicações e é universal.' },
c609: { c: 'Você desenhou seis losangos no DER. Quantos deles viram tabela?',
        s: 'Somem: viram FK nos casos 1:N e 1:1, e tabela no caso N:N.' },

/* ── 7. Entidades e Atributos ───────────────────────────────────────── */
c701: { c: 'O enunciado fala em clientes, produtos e pedidos. Cada um desses vira uma coisa no banco.',
        s: 'Um agrupamento de informações com existência própria — vira tabela no físico.' },
c702: { s: 'Atributo é característica e vira coluna; tupla é a linha, o registro.' },
c703: { c: 'Você recebe o enunciado e tem cinco minutos. Por onde começar a leitura?',
        s: 'Substantivos costumam ser entidades; verbos costumam ser relacionamentos.' },
c704: { c: 'Você criou uma entidade CATEGORIA que só tem o campo "nome" e nada mais.',
        s: 'Dois — com um só, ela normalmente é agregada a outra entidade.' },
c705: { s: 'É o conjunto de todas as ocorrências de uma entidade, e seus elementos são distintos.' },
c706: { c: 'A entidade CD e o disco "Mais do Mesmo" na sua estante não são a mesma coisa.',
        s: 'Entidade é a categoria; instância é a ocorrência específica.' },
c707: { s: 'Simples é um valor só, composto se divide em partes, multivalorado tem vários valores.' },
c708: { c: 'Endereço e telefone parecem o mesmo tipo de problema, mas são coisas diferentes.',
        s: 'Composto é um valor dividido em partes; multivalorado são vários valores do mesmo tipo.' },
c709: { s: 'Asterisco depois do nome na notação textual, elipse dupla no DER.' },
c710: { c: 'O cliente liga pedindo para cadastrar o quarto telefone. Só existem três colunas.',
        s: 'Porque limita a quantidade e desperdiça espaço — o certo é criar uma tabela.' },
c711: { s: 'Fundamental tem existência própria; associativa nasce do relacionamento entre duas fundamentais.' },
c712: { c: 'Alguém criou uma entidade COR só para guardar a cor dos produtos.',
        s: 'Se tem características próprias e várias ocorrências, é entidade; se só descreve, é atributo.' },

/* ── 8. Chaves ──────────────────────────────────────────────────────── */
c801: { c: 'Você precisa achar uma linha específica entre um milhão, e achar só aquela.',
        s: 'Identifica unicamente cada tupla — e precisa ser única, exclusiva e imutável.' },
c802: { c: 'A tabela PEDIDO tem uma coluna COD_CLI. Ela não identifica o pedido; ela aponta para outro lugar.',
        s: 'Atributo que referencia a PK de outra tabela e sustenta o relacionamento.' },
c803: { c: 'Você quer listar os pedidos em ordem de data. Não precisa identificar nada, só ordenar.',
        s: 'Serve para classificação e pesquisa — não identifica unicamente.' },
c804: { c: 'Você está olhando uma coluna e não sabe dizer se ela é PK ou FK.',
        s: 'PK responde "quem sou eu?"; FK responde "quem eu referencio?".' },
c805: { c: 'O pedido 100 tem cinco itens. Se a PK fosse só o número do pedido, você teria cinco linhas iguais.',
        s: 'PK formada por mais de um atributo — é a combinação que identifica.' },
c806: { c: 'Tentativa: PRIMARY KEY (nr_pedido). O banco recusa a segunda linha do mesmo pedido.',
        s: 'Porque o mesmo pedido tem vários itens — só a combinação identifica uma linha.' },
c807: { c: 'Você usou o nome como chave. Aí entra o segundo "João Silva", e o primeiro se casa e muda de nome.',
        s: 'Porque pode repetir e pode mudar.' },
c808: { c: 'Uma tabela de logs em que nenhuma coluna é confiavelmente única.',
        s: 'Crie um — um código sequencial resolve.' },
c809: { c: 'Em CLIENTE_FONE, a coluna COD_CLI faz duas coisas ao mesmo tempo.',
        s: 'Sim — acontece em entidades fracas e em tabelas associativas.' },
c810: { c: 'As duas não são a chave primária, e por isso costumam ser confundidas.',
        s: 'Secundária é para buscar e ordenar; estrangeira é para ligar tabelas.' },
c811: { s: 'Sublinhado — a elipse sublinhada.' },

/* ── 9. Relacionamentos e Cardinalidade ─────────────────────────────── */
c901: { c: 'No enunciado: "o cliente solicita projetos". Esse verbo vai virar alguma coisa no desenho.',
        s: 'É a associação entre entidades, quase sempre um verbo, desenhada como losango.' },
c902: { c: 'Um departamento tem quantos funcionários? E um funcionário está em quantos departamentos?',
        s: 'Quantas ocorrências de cada lado podem se relacionar: 1:1, 1:N ou N:N.' },
c903: { s: 'Um nome (verbo), a opcionalidade (deve/pode) e a cardinalidade.' },
c904: { c: 'Você desenhou DEPARTAMENTO 1 — 1 GERENTE e ficou com uma sensação estranha.',
        s: 'Não deveriam ser uma entidade só? E amanhã isso não vira 1:N?' },
c905: { c: 'Você tem DEPARTAMENTO e FUNCIONARIO. Em qual das duas tabelas vai a coluna de ligação?',
        s: 'O lado 1 tem os dados básicos; a FK desce para o lado N.' },
c906: { c: 'Tente escrever uma tabela ALUNO com uma coluna "disciplinas" para cinco disciplinas.',
        s: 'Porque cada linha tem um valor por coluna — precisa de uma tabela associativa no meio.' },
c907: { s: 'Pessoa e CPF é 1:1; turma e aluno é 1:N; produto e fornecedor é N:N.' },
c908: { s: '1:1 departamento e gerente; 1:N cliente e pedido; N:N autor e livro.' },
c909: { c: 'Você colocou o número do pedido dentro da tabela CLIENTE. O cliente tem 40 pedidos.',
        s: 'Inverter o lado da FK — ela vai no lado N, nunca no lado 1.' },
c910: { c: 'Antes de escrever qualquer CREATE TABLE, é a cardinalidade que decide o formato.',
        s: 'Porque é ela que decide se nasce uma tabela e de que lado fica a chave.' },

/* ── 10. Grau e Auto-relacionamento ─────────────────────────────────── */
c1001: { c: 'Duas perguntas parecidas, respostas diferentes: "quantos de cada lado?" e "quantas entidades?".',
         s: 'Quantas entidades participam do relacionamento: 1, 2, 3...' },
c1002: { c: 'Prova: "funcionário supervisiona funcionário — qual o grau e qual a cardinalidade?".',
         s: 'Cardinalidade conta ocorrências de cada lado; grau conta entidades participantes.' },
c1003: { c: 'O chefe do funcionário também é um funcionário, cadastrado na mesma tabela.',
         s: 'Uma entidade se relaciona com ela mesma, com rótulos de papel nas pontas.' },
c1004: { s: 'Supervisão entre funcionários, pai e filho, categoria e subcategoria, peça composta de peças.' },
c1005: { c: 'Tentação comum: criar uma entidade SUPERVISOR ao lado de FUNCIONARIO.',
         s: 'Porque o supervisor é um funcionário — criar outra entidade duplicaria tudo.' },
c1006: { c: 'No desenho, o retângulo FUNCIONARIO aparece nas duas pontas do losango.',
         s: 'Errado: é grau 1, porque há uma única entidade participando.' },
c1007: { c: 'Você recebe seis tabelas e precisa achar o auto-relacionamento sem ler o enunciado.',
         s: 'Uma FK que aponta para a própria tabela.' },
c1008: { c: 'Professor, aluno e disciplina num losango só — e o desenho fica desconfortável.',
         s: 'Três entidades no mesmo losango; quando fica artificial, use agregação.' },

/* ── 11. Entidade fraca e associativa ───────────────────────────────── */
c1101: { c: 'Dois funcionários têm um dependente chamado Pedro. Como identificar cada um deles?',
         s: 'Depende de outra entidade para ser identificada — retângulo duplo no DER.' },
c1102: { c: 'Você escreveu DEPENDENTE(nome PK). O banco aceita, mas o modelo está errado.',
         s: 'Porque o nome sozinho não identifica — a PK precisa incluir a chave do funcionário.' },
c1103: { s: 'Relacionamento identificador.' },
c1104: { c: 'ALUNO e DISCIPLINA são N:N. Alguma coisa precisa nascer no meio dos dois.',
         s: 'A estrutura que resolve um N:N, formada pela união das PKs das duas entidades.' },
c1105: { c: 'FORNECE guarda prazo, preço e quantidade. Nenhum deles é do material nem do fornecedor.',
         s: 'É a associativa que carrega atributos próprios do relacionamento.' },
c1106: { c: 'As duas aparecem como retângulo duplo com chave composta. Então qual é a diferença real?',
         s: 'A fraca vem de dependência de existência; a associativa vem de resolver um N:N.' },
c1107: { c: 'O empregado 10 trabalha 20 horas no projeto A e 15 no projeto B.',
         s: 'Ao relacionamento — horas depende da combinação empregado mais projeto.' },
c1108: { s: 'Mestre tem os dados principais (lado 1); detalhe depende dela (lado N).' },
c1109: { c: 'Você abre o esquema e vê uma tabela com duas FKs formando a chave e nada mais.',
         s: 'Que é um N:N resolvido — uma entidade associativa.' },
c1110: { c: 'Exercício direto: transformar um N:N com atributo numa tabela pronta.',
         s: 'ALUNO_DISCIPLINA com as duas chaves formando a PK, mais a nota.' },

/* ── 12. Especialização, Generalização, Agregação ───────────────────── */
c1201: { c: 'Todo engenheiro é funcionário, mas só engenheiro tem CREA e especialidade.',
         s: 'Criar entidades mais específicas a partir de uma geral — a relação "é-um", com triângulo.' },
c1202: { s: 'Mesma relação em direções opostas: especializar é ir do geral ao específico, generalizar é o inverso.' },
c1203: { c: 'Um funcionário pode ser engenheiro e gerente ao mesmo tempo? O símbolo responde.',
         s: 'Especialização exclusiva — a entidade pertence a apenas um subconjunto.' },
c1204: { c: 'Uma secretária é uma funcionária. Um funcionário tem um departamento. Não é a mesma relação.',
         s: '"É-um" é especialização; "tem-um" é relacionamento comum.' },
c1205: { c: 'O hospital precisa acompanhar não o médico e não o paciente, mas o atendimento entre os dois.',
         s: 'Tratar um relacionamento como entidade, para que ele participe de outro relacionamento.' },
c1206: { c: 'Materiais, requisições e pedidos num losango só — e o desenho não convence ninguém.',
         s: 'Quando o ternário fica artificial e um relacionamento precisa participar de outro.' },
c1207: { c: 'As duas transformam um relacionamento em algo que se relaciona. Então qual usar?',
         s: 'Associativa resolve N:N entre duas; agregação liga um relacionamento a uma terceira entidade.' },
c1208: { c: 'Você precisa escrever as duas tabelas e marcar a chave herdada.',
         s: 'O CPF do engenheiro é PK e FK ao mesmo tempo.' },
c1209: { c: 'Você copiou nome e salário para dentro de ENGENHEIRO, GERENTE e SECRETARIA.',
         s: 'Repetir os atributos do pai em cada especialização em vez de herdá-los.' },

/* ── 13. Integridade referencial ────────────────────────────────────── */
c1301: { c: 'Existe um pedido no banco apontando para o cliente 99. O cliente 99 nunca existiu.',
         s: 'A regra que garante que toda FK aponte para um registro que realmente existe.' },
c1302: { s: 'Qualquer inclusão, exclusão ou alteração que deixe uma FK sem correspondente.' },
c1303: { c: 'Você tenta apagar o cliente 1, que tem 40 pedidos gravados.',
         s: 'Ou o SGBD bloqueia (RESTRICT), ou apaga os dependentes junto (CASCADE).' },
c1304: { c: 'São duas regras, e cada uma cuida de uma chave diferente.',
         s: 'Referencial cuida da FK; de entidade cuida da PK.' },
c1305: { c: 'Exercício de marcar qual linha está inválida numa lista curta.',
         s: 'O pedido com cod_cli = 5, porque não existe cliente 5.' },
c1306: { c: 'Você criou as tabelas sem declarar nenhuma FOREIGN KEY e espera que o banco proteja.',
         s: 'Errado: ela precisa ser declarada via FK e constraints no modelo físico.' },

/* ── 14. Mapeamento ─────────────────────────────────────────────────── */
c1401: { c: 'Duas entidades no DER, uma forte e uma fraca. As tabelas não saem iguais.',
         s: 'Forte vira tabela com seus atributos; fraca leva junto a PK da forte, compondo a própria PK.' },
c1402: { c: 'Você tem CLIENTE 1 — N PEDIDO e está prestes a criar uma terceira tabela. Não crie.',
         s: 'Não gera tabela: a chave do lado 1 desce como FK para o lado N, fora da PK.' },
c1403: { c: 'ALUNO e DISCIPLINA, com a nota de cada aluno em cada disciplina.',
         s: 'Gera tabela com as duas PKs mais os atributos do relacionamento.' },
c1404: { c: 'Todo país tem uma capital, mas nem toda cidade é capital. Onde fica a chave?',
         s: 'Pela participação total — a chave vai para o lado que participa sempre.' },
c1405: { c: 'O cliente tem três telefones hoje e pode ter cinco amanhã.',
         s: 'Vira tabela nova, com o atributo mais a PK da entidade.' },
c1406: { c: 'Uma conta é corrente ou poupança, nunca as duas, e sempre é uma das duas.',
         s: 'Forma 1 sempre vale; forma 2 só se a especialização for exclusiva e total.' },
c1407: { c: 'Nos dois casos a chave de uma tabela vai parar em outra. O destino dela é que muda.',
         s: 'No 1:N ela é só FK e fica fora da PK; na fraca ela entra na PK.' },
c1408: { c: 'A mesma pergunta com duas respostas opostas — e a explicação está na forma da tabela.',
         s: 'No 1:N a FK resolve sozinha; no N:N não cabe numa tabela só.' },
c1409: { s: 'Criar tabela para 1:N, esquecer a chave da forte na fraca, errar o lado no 1:1 e ignorar o multivalorado.' },
c1410: { c: 'Três mapeamentos rápidos, um de cada tipo, para treinar o automatismo.',
         s: 'FK em CD, tabela AUTOR_MUSICA, tabela CLIENTE_FONE.' },
c1411: { s: 'Como entidades e relacionamentos normais — as regras são as mesmas.' },

/* ── 15. Aspecto temporal ───────────────────────────────────────────── */
c1501: { c: 'O RH pergunta: você quer saber o salário de hoje, ou todos os salários que ele já teve?',
         s: 'Atual é como está agora; temporal é agora mais como esteve no passado.' },
c1502: { c: 'O salário do empregado mudou seis vezes em quatro anos, e o RH quer os seis valores.',
         s: 'Vira uma nova entidade, com data.' },
c1503: { c: 'Cada empregado tem uma mesa. Mas o RH quer saber todas as mesas por onde ele passou.',
         s: 'Vira N:N com data — os dois lados passam a ser "muitos".' },
c1504: { c: 'João sentou na Mesa 10 em 2023, saiu, e voltou para a Mesa 10 em 2025.',
         s: 'Porque o mesmo par pode se relacionar mais de uma vez, e a data separa as ocorrências.' },
c1505: { c: 'O banco cresceu 400 GB guardando histórico de dez anos. Alguma coisa precisa sair.',
         s: 'Arquivar guarda o detalhe fora do banco; estatística guarda só o resumo e joga o detalhe fora.' },
c1506: { c: 'Você arquivou os pedidos de 2019, mas os clientes daqueles pedidos também saíram.',
         s: 'Recuperar uma entidade exige recuperar aquelas de que ela depende.' },
c1507: { c: 'Alguém criou as colunas salario1, salario2 e salario3 para guardar o histórico.',
         s: 'Guardar histórico em colunas fixas em vez de criar uma entidade.' },
c1508: { s: 'HISTORICO_CARGO com cod_emp e data formando a chave, mais o cargo.' },

/* ── 16. Normalização ───────────────────────────────────────────────── */
c1601: { c: 'Uma tabela só com pedido, itens, departamentos e funcionários misturados.',
         s: 'Organizar as tabelas para não misturar assuntos diferentes no mesmo lugar.' },
c1602: { c: 'Se você lembrar de uma frase só sobre formas normais, que seja esta.',
         s: '1FN tira repetição, 2FN olha a chave composta, 3FN olha dependência entre não-chaves.' },
c1603: { c: 'A tabela tem uma linha por item, e todos os dados do pedido repetidos em cada linha.',
         s: 'Elimina grupos de repetição — não toda a redundância.' },
c1604: { c: 'A chave é NR_PEDIDO + ITEM. Alguns campos dependem só de uma metade dela.',
         s: 'Os não-chave dependem da chave inteira? Só vale para tabelas com chave composta.' },
c1605: { c: 'Sobrou o nome do departamento na tabela de pedidos, e um campo QTD_TOTAL.',
         s: 'Não-chave que depende de outro não-chave, e atributos calculados.' },
c1606: { c: 'Os dois nomes aparecem juntos na prova e são fáceis de trocar.',
         s: 'Parcial depende de parte da chave; transitiva depende de outro não-chave.' },
c1607: { c: 'Cinco itens no mesmo pedido, cada um numa linha, com data e departamento repetidos.',
         s: 'O grupo de repetição: os itens saem para ITENS_PEDIDO.' },
c1608: { c: 'A chave é NR_PEDIDO + ITEM. "Lápis" depende do pedido ou do número do item?',
         s: 'Porque MATERIAL não depende da chave inteira — só do próprio material.' },
c1609: { c: 'Sobraram DEPTO_ORIGEM, FUNC_SOL e um total somado à mão.',
         s: 'Departamento e funcionário viram tabelas, e QTD_TOTAL é apagado por ser calculado.' },
c1610: { c: 'Alguém edita a quantidade de um item direto no banco e esquece de atualizar o total.',
         s: 'Porque é a soma dos itens — se armazenado, pode divergir da soma real.' },
c1611: { c: 'Duas coisas que a 3FN tira da tabela, por motivos diferentes.',
         s: 'Redundância é repetir a mesma informação; derivado é o que pode ser calculado.' },
c1612: { s: 'Achar que a 1FN resolve tudo, usar 2FN sem chave composta, manter totais e pular a ordem.' },
c1613: { c: 'Exercício real da aula: uma nota fiscal com itens, destinatário e transportador.',
         s: 'NOTA, ITENS_NOTA, PRODUTO, DESTINATARIO e TRANSPORTADOR — sem os campos calculados.' },
c1614: { c: 'Exercício real da aula: uma folha de controle de estoque com dois funcionários envolvidos.',
         s: 'CONTROLE, ITENS_CONTROLE, PECA, FUNCIONARIO e SETOR.' },

/* ── 17. Estudos de caso ────────────────────────────────────────────── */
c1701: { c: 'Você recebe um enunciado novo e a folha em branco. A sequência é sempre a mesma.',
         s: 'Substantivos, atributos, verbos, cardinalidade, atributos do relacionamento, casos especiais, mapeamento.' },
c1702: { c: 'É o passo que separa quem tira 6 de quem tira 10 — a varredura final antes de mapear.',
         s: 'Auto-relacionamento, fraca, multivalorado, especialização, generalização, agregação e N:N.' },
c1703: { c: 'O enunciado dá seis tabelas prontas e pede o DER. Você precisa traduzir de volta.',
         s: 'Tabela vira entidade, coluna vira atributo, FK indica relacionamento, intermediária indica N:N.' },
c1704: { c: 'Duas pistas diferentes no esquema, apontando para duas estruturas diferentes.',
         s: 'Fraca: a PK começa com a PK de outra. Auto-relacionamento: a FK aponta para a própria tabela.' },
c1705: { c: 'A tabela Casamento tem MaridoPessoaID e EsposaPessoaID — as duas apontam para Pessoa.',
         s: 'Porque PESSOA participa em dois papéis, marido e esposa — com um retângulo só.' },
c1706: { c: 'Duas turmas entregaram cardinalidades diferentes. As duas foram aceitas.',
         s: 'A leitura N:1 é mais defensável, mas o que salva é escrever a hipótese embaixo do desenho.' },
c1707: { c: 'É o exercício que junta os três casos especiais mais cobrados num diagrama só.',
         s: 'Entidade fraca, auto-relacionamento, N:N com atributo, e a tabela que nasce do N:N.' },
c1708: { c: 'Duas colunas diferentes ligam Empregado a Departamento: DepNum e IdentGer.',
         s: 'Trabalha é N:1; gerencia é 1:1.' },
c1709: { c: 'Uma turma escreveu POSSUIR, a outra escreveu TEM. Nenhuma perdeu ponto.',
         s: 'Cardinalidades, entidade fraca, auto-relacionamento e o N:N com atributo.' },
c1710: { c: 'Um diagrama só, com três estruturas especiais desenhadas ao mesmo tempo.',
         s: 'Especialização, atributo multivalorado e atributos pendurados no losango.' },
c1711: { c: 'A resposta final do exercício — oito relações com todas as chaves marcadas.',
         s: 'Oito tabelas, com ENGENHEIRO herdando o CPF e CLIENTE_FONE separado.' },
c1712: { c: 'Uma planilha de pedidos com colunas de subtotal e total já somados.',
         s: 'Chave repetida em outra tabela indica relacionamento — e os totais somem na 3FN.' },
c1713: { c: 'O diagrama mais completo da disciplina, feito a partir de uma ficha de manutenção.',
         s: 'Dois: SERV_PRESTADO e SOL_PRESTADA, ambos saindo de ATENDIMENTO.' },
c1714: { c: 'Falta uma semana para a prova e você quer um exercício que cubra tudo de uma vez.',
         s: 'Refazer o MER do atendimento técnico do zero e comparar com a resolução.' }

};
